### ISSUE TITLE
[Smartswitch] Orchagent is crashing when the MGMT_VRF is enabled

### ISSUE THREAD

**Issue by vivekrnv** [sonic-net/sonic-buildimage#19638] opened 2024-07-19 21:28 UTC
#### Description

When the MGMT_VRF_CONFIG is present, zmq_bind fails in orchagent and aborts. Seen on smartswitch platforms

#### Steps to reproduce the issue:
1. Add the MGMT_VRF config
```
"MGMT_VRF_CONFIG": {"vrf_global": {
       "mgmtVrfEnabled": "true"}}
```

2. Do config reload or reboot

or run the following test `test_syslog_config_work_after_reboot` 

#### Describe the results you received:

```
Jul  8 16:09:52.748231 r-smartswitch-03 ERR swss#orchagent: :- mqPollThread: zmq_bind failed on endpoint: tcp://10.210.25.4:8100, zmqerrno: 99
```

#### Output of `show version`:

```
(paste your output here)
```
#### Output of `show techsupport`:

```
(paste your output here or download and attach the file here )
```

**Comment by vivekrnv** [comment] 2024-07-19 21:29
@liuh-80 @Pterosaur @prsunny Please check

**Comment by vivekrnv** [comment] 2024-07-31 15:35
https://github.com/sonic-net/sonic-buildimage/blob/master/dockers/docker-orchagent/orchagent.sh#L87

**Comment by judyjoseph** [comment] 2024-07-31 16:41
@liuh-80 could you take a look at this issue

**Comment by liuh-80** [comment] 2024-08-12 02:24
will check and fix the issue soon

**Comment by liuh-80** [comment] 2024-09-24 02:22
The root cause of this issue is because currently ZMQ not bind to VRF by ZMQ_BINDTODEVICE when VRF enabled:
https://libzmq.readthedocs.io/en/latest/zmq_setsockopt.html
This need code change in sonic-swss-common/sonic-gnmi/sonic-buildimage.

**Comment by liuh-80** [comment] 2024-11-05 01:06
All PR merged, manually verified orchagent not crash after enable vrf, close this bug.

**Closed by liuh-80** 2024-11-05 01:06 UTC
Labels: Triaged, MSFT
