### ISSUE TITLE
[202205] [T2] - Removing and adding neighbors back on asic, creates 'Malformed communities attribute' error 

### ISSUE THREAD

**Issue by sanjair-git** [sonic-net/sonic-buildimage#20055] opened 2024-08-28 15:20 UTC
#### Description

- On **202205** sonic-buildimage, as part of the test '_test_TSA_B_C_with_no_neighbors_', it is expected that removing and adding neighbors back on one of the asic shouldn't create any errors/issue.

- But when the neighbors are added back after removal, bgpcfgd process of the respective asic, throws the following '_Malformed communities attribute_' error on the line card. 

`Aug 27 19:03:58.468194 ixre-egl-board1 ERR bgp0#bgpcfgd: command execution returned 13. Command: '['vtysh', '-f', '/tmp/tmpxbt4ngqn']', stdout: '% Malformed communities attribute#012% Malformed communities attribute#012% Malformed communities attribute#012% Malformed communities attribute#012', stderr: 'line 239: Failure to communicate[13] to bgpd, line:   set community community-list FABRIC_INFRA_COMMUNITY#012#012line 774: Failure to communicate[13] to bgpd, line:   set community community-list FABRIC_INFRA_COMMUNITY#012#012line 1991: Failure to communicate[13] to bgpd, line:   set community community-list FABRIC_INFRA_COMMUNITY#012#012line 2715: Failure to communicate[13] to bgpd, line:   set community community-list FABRIC_INFRA_COMMUNITY#012#012'`

#### Steps to reproduce the issue:
1. Remove neighbors on one of the asic using the following command, for example:

> sudo sonic-db-cli -n asic0 CONFIG_DB keys "BGP_NEI*" | xargs sonic-db-cli -n asic0 CONFIG_DB del

2. Add all the neighbors back using sonic-cfggen command as shown below for example:

> sudo sonic-cfggen -n asic0 -a '{"BGP_NEIGHBOR": {"10.0.0.5": {"rrclient": "0", "name": "ARISTA03T3", "local_addr": "10.0.0.4", "nhopself": "0", "admin_status": "up", "holdtime": "10", "asn": "65200", "keepalive": "3"}, "10.0.0.1": {"rrclient": "0", "name": "ARISTA01T3", "local_addr": "10.0.0.0", "nhopself": "0", "admin_status": "up", "holdtime": "10", "asn": "65200", "keepalive": "3"}, "fc00::a": {"rrclient": "0", "name": "ARISTA03T3", "local_addr": "fc00::9", "nhopself": "0", "admin_status": "up", "holdtime": "10", "asn": "65200", "keepalive": "3"}, "fc00::2": {"rrclient": "0", "name": "ARISTA01T3", "local_addr": "fc00::1", "nhopself": "0", "admin_status": "up", "holdtime": "10", "asn": "65200", "keepalive": "3"}}}' --write-to-db

#### Describe the results you received:

- Once the neighbors are added back, it is seen that bgpcfgd throws the following malformed communities attribute error as shown below,
`Aug 27 19:03:58.468194 ixre-egl-board1 ERR bgp0#bgpcfgd: command execution returned 13. Command: '['vtysh', '-f', '/tmp/tmpxbt4ngqn']', stdout: '% Malformed communities attribute#012% Malformed communities attribute#012% Malformed communities attribute#012% Malformed communities attribute#012', stderr: 'line 239: Failure to communicate[13] to bgpd, line:   set community community-list FABRIC_INFRA_COMMUNITY#012#012line 774: Failure to communicate[13] to bgpd, line:   set community community-list FABRIC_INFRA_COMMUNITY#012#012line 1991: Failure to communicate[13] to bgpd, line:   set community community-list FABRIC_INFRA_COMMUNITY#012#012line 2715: Failure to communicate[13] to bgpd, line:   set community community-list FABRIC_INFRA_COMMUNITY#012#012'`

#### Describe the results you expected:

- No errors are expected while applying the neighbors back on asic.

#### Output of `show version`:

```
show version

SONiC Software Version: SONiC.20220532.68
SONiC OS Version: 11
Distribution: Debian 11.9
Kernel: 5.10.0-23-2-amd64
Build commit: 40f5f9cf13
Build date: Fri Aug  9 09:18:44 UTC 2024
Built by: azureuser@479f324cc000000

```
#### Output of `show techsupport`:

```
(paste your output here or download and attach the file here )
```

**Comment by abdosi** [comment] 2024-08-28 17:42
@tjchadaga please look into this.

**Comment by saksarav-nokia** [comment] 2024-08-28 18:18
@tjchadaga , Sanjay tried the previous production images and seems this issue got introduced in image 66

**Comment by saksarav-nokia** [comment] 2024-08-29 16:45
[bgpcfg_policy_60.txt](https://github.com/user-attachments/files/16802540/bgpcfg_policy_60.txt)
[bgpcfg_policy_68.txt](https://github.com/user-attachments/files/16802541/bgpcfg_policy_68.txt)
Hi @tjchadaga , Please find the bgp config applied by bgpcfgd to frr when the bgp neighbors are applied to config_db after deleting it . Attached for both image 60 and 68.  The " set community community-list FABRIC_INFRA_COMMUNITY" is not applied in image 60 ,but in image 68 which is causing the "Malformed community attribute" error. You can even manually apply this file using vtysh -c "file" and you will see the error with that line. Also this is reproducible only in uplink line cards and not in downlink cards.

route-map TO_AZNG_MIGRATION_FILTER_V4 permit 2
  match as-path T2_LOOPBACK
  set community community-list FABRIC_INFRA_COMMUNITY
!

route-map TO_AZNG_MIGRATION_FILTER_V6 permit 2
  match as-path T2_LOOPBACK
  set community community-list FABRIC_INFRA_COMMUNITY
!

**Comment by saksarav-nokia** [comment] 2024-08-29 17:51
Looks like the template /usr/share/sonic/templates/bgpd/templates/msft.general/v4.spine.ah/policy.conf.j2 got added with "set community community-list FABRIC_INFRA_COMMUNITY" and causing this error.

**Comment by tjchadaga** [comment] 2024-08-29 18:26
thanks for narrowing this down, @saksarav-nokia. @abdosi will raise a PR for this

**Comment by rlhui** [comment] 2024-09-18 17:08
@abdosi fixed in internal code.

**Closed by rlhui** 2024-09-18 17:08 UTC
Labels: P0, Chassis :robot:, Issue for 202205
