### ISSUE TITLE
[202305] Build failure on latest 202305 in target sonic-p4rt_0.0.1_amd64.deb

### ISSUE THREAD

**Issue by stepanblyschak** [sonic-net/sonic-buildimage#16087] opened 2023-08-09 16:25 UTC
#### Description

Observed on hash b226ae0699b45808364863a137d27de353cff3ee.

#### Steps to reproduce the issue:
1. git clone -b 202305 git@github.com:azure/sonic-buildimage
2. cd sonic-buildimage
3. make init
4. make configure PLATFORM=mellanox
5. make target/sonic-mellanox.bin

#### Describe the results you received:

```
[ FAIL LOG START ] [ target/debs/bullseye/sonic-p4rt_0.0.1_amd64.deb ]
Build start time: Wed Aug 9 15:31:30 UTC 2023
[ REASON ] :      target/debs/bullseye/sonic-p4rt_0.0.1_amd64.deb does not exist   NON-EXISTENT PREREQUISITES: target/debs/bullseye/libswsscommon-dev_1.0.0_amd64.deb-install
[ FLAGS  FILE    ] : [mellanox amd64 bullseye bullseye]
[ FLAGS  DEPENDS ] : [mellanox amd64 bullseye bullseye]
[ FLAGS  DIFF    ] : []
make[1]: warning: -j12 forced in submake: resetting jobserver mode.
make[1]: Entering directory '/sonic/src/sonic-p4rt'
function cleanup {
# Note: make seems to hang if Bazel is still running
cd /sonic/src/sonic-p4rt/sonic-pins && bazel  shutdown
}
trap cleanup EXIT
pushd ./sonic-pins
bazel  build --fission=yes --features=per_object_debug_info --override_repository=sonic_swss_common=/sonic/src/sonic-swss-common -c opt //p4rt_app:p4rt_deb //p4rt_app:p4rt_dbg_deb
bazel  test --fission=yes --features=per_object_debug_info --override_repository=sonic_swss_common=/sonic/src/sonic-swss-common -c opt //p4rt_app/...
cd ./bazel-bin/p4rt_app
mv sonic-p4rt_0.0.1_amd64.deb sonic-p4rt-dbgsym_0.0.1_amd64.deb /sonic/target/debs/bullseye/
popd
/sonic/src/sonic-p4rt/sonic-pins /sonic/src/sonic-p4rt
/usr/share/depot_tools/vpython3: line 48: /usr/share/depot_tools/.cipd_bin/vpython3: No such file or directory
/usr/share/depot_tools/vpython3: line 48: /usr/share/depot_tools/.cipd_bin/vpython3: No such file or directory
make[1]: *** [Makefile:34: /sonic/target/debs/bullseye/sonic-p4rt_0.0.1_amd64.deb] Error 127
make[1]: Leaving directory '/sonic/src/sonic-p4rt'
[  FAIL LOG END  ] [ target/debs/bullseye/sonic-p4rt_0.0.1_amd64.deb ]
[ 01 ] [ target/docker-config-engine-bullseye.gz ]
[ 02 ] [ target/python-wheels/bullseye/sonic_platform_common-1.0-py3-none-any.whl ]
Makefile.work:602: recipe for target 'target/sonic-mellanox.bin' failed
make[1]: *** [target/sonic-mellanox.bin] Error 2
make[1]: Leaving directory '/builds2/stepanb/202305/sonic-buildimage'
Makefile:39: recipe for target 'target/sonic-mellanox.bin' failed
make: *** [target/sonic-mellanox.bin] Error 2
```

#### Describe the results you expected:

Successful build

#### Output of `show version`:
N/A
#### Output of `show techsupport`:
N/A

**Comment by roger530-ho** [comment] 2023-08-10 07:27
It seems that due to a permission issue with the setup of the CIPD_CLIENT_TMP in /usr/share/depot_tools/cipd, the cipd_bin_setup.sh has failed.

**Comment by puffc** [comment] 2023-08-11 06:07
Observed the same problem on master when building vs target.
<pre>
[ FAIL LOG START ] [ target/debs/bullseye/sonic-p4rt_0.0.1_amd64.deb ]
Build start time: Fri Aug 11 03:40:46 UTC 2023
[ REASON ] :      target/debs/bullseye/sonic-p4rt_0.0.1_amd64.deb does not exist   NON-EXISTENT PREREQUISITES: target/debs/bullseye/libswsscommon-dev_1.0.0_amd64.deb-install
[ FLAGS  FILE    ] : []
[ FLAGS  DEPENDS ] : []
[ FLAGS  DIFF    ] : []
make[1]: warning: -j8 forced in submake: resetting jobserver mode.
make[1]: Entering directory '/sonic/src/sonic-p4rt'
function cleanup {
# Note: make seems to hang if Bazel is still running
cd /sonic/src/sonic-p4rt/sonic-pins && bazel  shutdown
}
trap cleanup EXIT
pushd ./sonic-pins
bazel  build --fission=yes --features=per_object_debug_info --override_repository=sonic_swss_common=/sonic/src/sonic-swss-common -c opt //p4rt_app:p4rt_deb //p4rt_app:p4rt_dbg_deb
bazel  test --fission=yes --features=per_object_debug_info --override_repository=sonic_swss_common=/sonic/src/sonic-swss-common -c opt //p4rt_app/...
cd ./bazel-bin/p4rt_app
mv sonic-p4rt_0.0.1_amd64.deb sonic-p4rt-dbgsym_0.0.1_amd64.deb /sonic/target/debs/bullseye/
popd
/sonic/src/sonic-p4rt/sonic-pins /sonic/src/sonic-p4rt
/usr/share/depot_tools/vpython3: line 48: /usr/share/depot_tools/.cipd_bin/vpython3: No such file or directory
/usr/share/depot_tools/vpython3: line 48: /usr/share/depot_tools/.cipd_bin/vpython3: No such file or directory
make[1]: *** [Makefile:34: /sonic/target/debs/bullseye/sonic-p4rt_0.0.1_amd64.deb] Error 127
make[1]: Leaving directory '/sonic/src/sonic-p4rt'
[  FAIL LOG END  ] [ target/debs/bullseye/sonic-p4rt_0.0.1_amd64.deb ]
make: *** [slave.mk:685: target/debs/bullseye/sonic-p4rt_0.0.1_amd64.deb] Error 1
make: *** Waiting for unfinished jobs....
</pre>

**Comment by puffc** [comment] 2023-08-12 05:25
> Observed the same problem on master when building vs target.
> 
> [ FAIL LOG START ] [ target/debs/bullseye/sonic-p4rt_0.0.1_amd64.deb ]
> Build start time: Fri Aug 11 03:40:46 UTC 2023
> [ REASON ] :      target/debs/bullseye/sonic-p4rt_0.0.1_amd64.deb does not exist   NON-EXISTENT PREREQUISITES: target/debs/bullseye/libswsscommon-dev_1.0.0_amd64.deb-install
> [ FLAGS  FILE    ] : []
> [ FLAGS  DEPENDS ] : []
> [ FLAGS  DIFF    ] : []
> make[1]: warning: -j8 forced in submake: resetting jobserver mode.
> make[1]: Entering directory '/sonic/src/sonic-p4rt'
> function cleanup {
> # Note: make seems to hang if Bazel is still running
> cd /sonic/src/sonic-p4rt/sonic-pins && bazel  shutdown
> }
> trap cleanup EXIT
> pushd ./sonic-pins
> bazel  build --fission=yes --features=per_object_debug_info --override_repository=sonic_swss_common=/sonic/src/sonic-swss-common -c opt //p4rt_app:p4rt_deb //p4rt_app:p4rt_dbg_deb
> bazel  test --fission=yes --features=per_object_debug_info --override_repository=sonic_swss_common=/sonic/src/sonic-swss-common -c opt //p4rt_app/...
> cd ./bazel-bin/p4rt_app
> mv sonic-p4rt_0.0.1_amd64.deb sonic-p4rt-dbgsym_0.0.1_amd64.deb /sonic/target/debs/bullseye/
> popd
> /sonic/src/sonic-p4rt/sonic-pins /sonic/src/sonic-p4rt
> /usr/share/depot_tools/vpython3: line 48: /usr/share/depot_tools/.cipd_bin/vpython3: No such file or directory
> /usr/share/depot_tools/vpython3: line 48: /usr/share/depot_tools/.cipd_bin/vpython3: No such file or directory
> make[1]: *** [Makefile:34: /sonic/target/debs/bullseye/sonic-p4rt_0.0.1_amd64.deb] Error 127
> make[1]: Leaving directory '/sonic/src/sonic-p4rt'
> [  FAIL LOG END  ] [ target/debs/bullseye/sonic-p4rt_0.0.1_amd64.deb ]
> make: *** [slave.mk:685: target/debs/bullseye/sonic-p4rt_0.0.1_amd64.deb] Error 1
> make: *** Waiting for unfinished jobs....

Fixed by #16114

**Comment by liushilongbuaa** [comment] 2023-08-14 03:21
saiarcot895 has a PR to fix.
Root cause is code change in third-party repo change in https://chromium.googlesource.com/chromium/tools/depot_tools

**Closed** 2023-08-16 21:18 UTC
Labels: Triaged, MSFT

**Comment by Yagami-Jiang** [comment] 2023-08-17 08:37
Yes, when i compile the SONiC image of the master branch in github.
If anyone has suggestions please let me know. Very Thx!


[ FAIL LOG START ] [ target/debs/bullseye/sonic-p4rt_0.0.1_amd64.deb ]
Build start time: Thu Aug 17 07:01:52 UTC 2023
[ REASON ] :      target/debs/bullseye/sonic-p4rt_0.0.1_amd64.deb does not exist   NON-EXISTENT PREREQUISITES: target/debs/bullseye/li                                                                             ll
[ FLAGS  FILE    ] : []
[ FLAGS  DEPENDS ] : []
[ FLAGS  DIFF    ] : []
make[1]: Entering directory '/sonic/src/sonic-p4rt'
function cleanup {
# Note: make seems to hang if Bazel is still running
cd /sonic/src/sonic-p4rt/sonic-pins && bazel  shutdown
}
trap cleanup EXIT
pushd ./sonic-pins
bazel  build --fission=yes --features=per_object_debug_info --override_repository=sonic_swss_common=/sonic/src/sonic-swss-common -c op                                                                             _dbg_deb
bazel  test --fission=yes --features=per_object_debug_info --override_repository=sonic_swss_common=/sonic/src/sonic-swss-common -c opt
cd ./bazel-bin/p4rt_app
mv sonic-p4rt_0.0.1_amd64.deb sonic-p4rt-dbgsym_0.0.1_amd64.deb /sonic/target/debs/bullseye/
popd
/sonic/src/sonic-p4rt/sonic-pins /sonic/src/sonic-p4rt
/usr/share/depot_tools/vpython3: line 52: /usr/share/depot_tools/.cipd_bin/vpython3: No such file or directory
/usr/share/depot_tools/vpython3: line 52: /usr/share/depot_tools/.cipd_bin/vpython3: No such file or directory
make[1]: *** [Makefile:34: /sonic/target/debs/bullseye/sonic-p4rt_0.0.1_amd64.deb] Error 127
make[1]: Leaving directory '/sonic/src/sonic-p4rt'
[  FAIL LOG END  ] [ target/debs/bullseye/sonic-p4rt_0.0.1_amd64.deb ]
make: *** [slave.mk:685: target/debs/bullseye/sonic-p4rt_0.0.1_amd64.deb] Error 1
make[1]: *** [Makefile.work:602: target/sonic-broadcom.bin] Error 2
make[1]: Leaving directory '/work/users/yajiang/yagami/SilverstoneV2/All/sonic-buildimage'
make: *** [Makefile:41: target/sonic-broadcom.bin] Error 2
