### ISSUE TITLE
Orchagent exiting due to unsupported SAI_*_ATTR_SELECTIVE_COUNTER_LIST attr

### ISSUE THREAD

**Issue by bofish-arista** [sonic-net/sonic-buildimage#20725] opened 2024-11-07 06:04 UTC
#### Description

Sonic-buildimage PR#20540 has incorporated SAI changes which includes latest sairedis, this in turn features changes to SAI, including SAI_PORT_ATTR_SELECTIVE_COUNTER_LIST, which does not appear to be supported yet by Broadcom.

As a result of this change, orchagent is exiting early in startup process.

Relevant links:
https://github.com/sonic-net/sonic-buildimage/pull/20540
https://github.com/sonic-net/sonic-sairedis/pull/1431
https://github.com/opencomputeproject/SAI/pull/1941

#### Steps to reproduce the issue:

Issue is seen during inialization of a standalone device.

#### Describe the results you received:

Orchagent exited with runtime error logged as shown below:

2024 Nov  4 17:44:07.612509 up500 ERR syncd#syncd: :- run: Runtime error: :- discover: when query SAI_PORT_ATTR_SELECTIVE_COUNTER_LIST (on SAI_OBJECT_TYPE_PORT RID oid:0x100000001) got value oid:0x7ffc4a7b45f0 objectTypeQuery returned NULL object type

#### Output of `show version`:

root@up322:~# show version

SONiC Software Version: SONiC.branch.master-ars.7cd2518e-buildimage.origin.master-nightly-slim-2024.10.31.20.12
SONiC OS Version: 12
Distribution: Debian 12.7
Kernel: 6.1.0-22-2-amd64
Build commit: 7f44814d7
Build date: Fri Nov  1 00:59:18 UTC 2024
Built by: jenkins@jenkins-arsonic-k8s-1-vfqtx

Platform: x86_64-arista_7060_cx32s
HwSKU: Arista-7060CX-32S-C32
ASIC: broadcom
ASIC Count: 1
Serial Number: SGD20254417
Model Number: DCS-7060CX-32S
Hardware Revision: 03.00
Uptime: 06:20:23 up 9 min,  2 users,  load average: 0.26, 0.98, 0.75
Date: Sat 02 Nov 2024 06:20:23

```
(paste your output here)
```
#### Output of `show techsupport`:

```
(paste your output here or download and attach the file here )
```

**Comment by kcudnik** [comment] 2024-11-08 08:02
Hi:

```
f23185d5 (Rajkumar-Marvell         2024-10-07 11:55:21 +0530 2627)     SAI_PORT_ATTR_SELECTIVE_COUNTER_LIST,
```
 
that attribute was recently added in 2024/10/7
 
```
SAI_PORT_ATTR_SELECTIVE_COUNTER_LIST (on SAI_OBJECT_TYPE_PORT RID oid:0x20100000000) got value oid:0x559ac8beda80 objectTypeQuery returned NULL object type
```

this attribute is LIST of counters, and it returned some OID value 0x559ac8beda80 on which OT returned NULL, and it should be SAI_OBJECT_TYPE_COUNTER as specified in SAI headers saiport.h, if it's returning NULL, that's a vendor bug 
 
and currently syncd on such error crashes, since we got OID but we don't know what type it is, this is invalid

so what should happened, when we have newer headers in SAI sairedis/syncd and we are using older vendor SAI, all unsupported attributes should return not implemented or not supported, instead of success, but it seams that vendor is returning some invalid value and success on this attribute

error comes from here: https://github.com/sonic-net/sonic-sairedis/blob/master/syncd/SaiDiscovery.cpp#L237

error could be also caused by DASH extensions (if vendor support DASH) since extensions range changed, and that change is not backward compatible: https://github.com/opencomputeproject/SAI/pull/2028

so what i expect is happening, vendor have some custom/private attribute after SAI_PORT_ATTR_END, on older version of SAI headers

**Comment by tjchadaga** [comment] 2024-11-08 18:34
@JaiOCP - could you please confirm the analysis above?

**Comment by bofish-arista** [comment] 2024-11-08 20:06
Hi @kcudnik - your assessment is correct.  There are some extensions added by the vendor which are causing the conflict.  The vendor implementation currently does not allow SAI to grow without introducting conflicts.   We have a ticket opened with them to get this addressed.

**Comment by kcudnik** [comment] 2024-11-08 21:29
Nice, I have proposal to update syncd and SAI metadata to add version on each attribute so discovery process will not exceed SAI_PORT_ATTR_END and any attr end if vendor is lover version than supported syncd headers, this will solve this issue for the future, I will work on this to address this issue

@lguohan for visibility

**Comment by kcudnik** [comment] 2024-11-08 21:30
> Hi @kcudnik - your assessment is correct. There are some extensions added by the vendor which are causing the conflict. The vendor implementation currently does not allow SAI to grow without introducting conflicts. We have a ticket opened with them to get this addressed.

We introduced custom attribute range for each attribute for vendors to prevent this behavior

**Comment by kcudnik** [comment] 2024-11-19 07:55
I created partial  one step to partial solution https://github.com/opencomputeproject/SAI/pull/2100, with this we will have attributes and SAI version per attribute,  you can read explanation here: https://github.com/opencomputeproject/SAI/issues/2099

**Comment by prgeor** [comment] 2024-11-20 16:14
@ying can you check with @kcudnik how to unblock master with SAI 11.x as 12.x may introduce regression?

**Comment by bradh352** [comment] 2024-11-28 18:54
Anyone tracking this issue, a simple workaround until a proper fix is created is here: https://github.com/bradh352/sonic-sairedis/commit/9f2a0b9

**Comment by kcudnik** [comment] 2024-11-28 19:30
on sairedis master this is already fixed partially: https://github.com/sonic-net/sonic-sairedis/pull/1470, this is checked in, but needs to be enabled by "-a" parameter in syncd init script

**Comment by kcudnik** [comment] 2024-11-28 19:32
also entire problem is not that simple, since custom attributes on cisco will be moved from v1.13 and v1.14 to different range

**Comment by bradh352** [comment] 2024-11-28 19:53
> on sairedis master this is already fixed partially: [sonic-net/sonic-sairedis#1470](https://github.com/sonic-net/sonic-sairedis/pull/1470), this is checked in, but needs to be enabled by "-a" parameter in syncd init script

I saw that but I didn't see the commit to SAI that actually tagged each attribute with a version.  That said, now that I'm looking harder at it, I see https://github.com/opencomputeproject/SAI/pull/2100 which is actually auto-generating a version header based on git tags.

Out of curiosity why make it opt-in?   Are there expected incompatibilities?

**Comment by kcudnik** [comment] 2024-11-28 21:45
for backward compatibility

**Comment by bradh352** [comment] 2024-12-01 15:12
I can confirm that adding the "-a" does indeed work on my TD3 switches.

**Comment by kcudnik** [comment] 2024-12-01 20:55
> I can confirm that adding the "-a" does indeed work on my TD3 switches.

nice !

**Comment by kcudnik** [comment] 2024-12-01 20:55
can we enable tahat ?

**Comment by bradh352** [comment] 2024-12-01 21:46
I think it would make sense for it to be enabled by default, that said I don't fully understand the backwards compatibility implications, perhaps there may be specific issues with various closed vendor blobs.  In my own branch (which I only use on Broadcom Trident 3) I always enable `-a`: https://github.com/bradh352/sonic-sairedis/commit/4fe35ae9

However, I don't see why it couldn't be moved into each ASIC-specific section that is validated to be ok:
https://github.com/bradh352/sonic-sairedis/blob/4fe35ae9ecb96f73568e3df318fabfd7bb2c124f/syncd/scripts/syncd_init_common.sh#L476

**Comment by kcudnik** [comment] 2024-12-02 14:29
can you make PR for sonic-sairedis to enable this feature by default ? i  think there are no implications for not enabling that in production, from other hand, if there are new  attributes that are not in official release then this needs to be disabled, but currently this feature is only implemented in discovery, user can still make invalid create/set/get of attrbitue that is vendor extention after ATTR_END

**Comment by bofish-arista** [comment] 2024-12-02 16:07
I've tried enabling -a flag in syncd init script and it is working for me.

**Comment by bradh352** [comment] 2024-12-02 16:17
> can you make PR for sonic-sairedis to enable this feature by default ? i think there are no implications for not enabling that in production, from other hand, if there are new attributes that are not in official release then this needs to be disabled, but currently this feature is only implemented in discovery, user can still make invalid create/set/get of attrbitue that is vendor extention after ATTR_END, but in normal operation this will not happen, since release versions are tested before production
> 
> but maybe it would make sense to also implement check on those operations too, in case some old libsai would be used in some weird case

done: https://github.com/sonic-net/sonic-sairedis/pull/1477

**Closed** 2024-12-06 18:00 UTC
Labels: Triaged, MSFT
