### ISSUE TITLE
getSupportedQueueCounters: FABRIC_QUEUE_STAT_COUNTER: counter errros messages in IMM with J2C+

### ISSUE THREAD

**Issue by saksarav-nokia** [sonic-net/sonic-buildimage#15586] opened 2023-06-22 17:53 UTC
#### Description

Th following error messages are seen in the IMM syslog 
Jun 16 14:48:10.659533 ixre-egl-board25 NOTICE syncd0#syncd: :- setQueueCounterList: FABRIC_QUEUE_STAT_COUNTER: queue oid:0x18d051500000001 does not has supported counters
Jun 16 14:48:10.660774 ixre-egl-board25 NOTICE syncd0#syncd: :- getSupportedQueueCounters: FABRIC_QUEUE_STAT_COUNTER: counter SAI_QUEUE_STAT_CURR_OCCUPANCY_LEVEL is not supported on queue oid:0x18e051500000001, rv: SAI_STATUS_NOT_SUPPORTED
Jun 16 14:48:10.660774 ixre-egl-board25 NOTICE syncd0#syncd: :- getSupportedQueueCounters: FABRIC_QUEUE_STAT_COUNTER: counter SAI_QUEUE_STAT_CURR_OCCUPANCY_BYTES is not supported on queue oid:0x18e051500000001, rv: SAI_STATUS_NOT_SUPPORTED
Jun 16 14:48:10.660799 ixre-egl-board25 NOTICE syncd0#syncd: :- getSupportedQueueCounters: FABRIC_QUEUE_STAT_COUNTER: counter SAI_QUEUE_STAT_WATERMARK_LEVEL is not supported on queue oid:0x18e051500000001, rv: SAI_STATUS_NOT_SUPPORTED
Jun 16 14:48:10.660799 ixre-egl-board25 NOTICE syncd0#syncd: :- setQueueCounterList: FABRIC_QUEUE_STAT_COUNTER: queue oid:0x18e051500000001 does not has supported counters
Jun 16 14:48:10.662189 ixre-egl-board25 NOTICE syncd0#syncd: :- getSupportedQueueCounters: FABRIC_QUEUE_STAT_COUNTER: counter SAI_QUEUE_STAT_CURR_OCCUPANCY_LEVEL is not supported on queue oid:0x18f051500000001, rv: SAI_STATUS_NOT_SUPPORTED
Jun 16 14:48:10.662204 ixre-egl-board25 NOTICE syncd0#syncd: :- getSupportedQueueCounters: FABRIC_QUEUE_STAT_COUNTER: counter SAI_QUEUE_STAT_CURR_OCCUPANCY_BYTES is not supported on queue oid:0x18f051500000001, rv: SAI_STATUS_NOT_SUPPORTED
Jun 16 14:48:10.662204 ixre-egl-board25 NOTICE syncd0#syncd: :- getSupportedQueueCounters: FABRIC_QUEUE_STAT_COUNTER: counter SAI_QUEUE_STAT_WATERMARK_LEVEL is not supported on queue oid:0x18f051500000001, rv: SAI_STATUS_NOT_SUPPORTED
Jun 16 14:48:10.662226 ixre-egl-board25 NOTICE syncd0#syncd: :- setQueueCounterList: FABRIC_QUEUE_STAT_COUNTER: queue oid:0x18f051500000001 does not has supported counters
Jun 16 14:48:10.663602 ixre-egl-board25 NOTICE syncd0#syncd: :- getSupportedQueueCounters: FABRIC_QUEUE_STAT_COUNTER: counter SAI_QUEUE_STAT_CURR_OCCUPANCY_LEVEL is not supported on queue oid:0x190051500000001, rv: SAI_STATUS_NOT_SUPPORTED
Jun 16 14:48:10.663602 ixre-egl-board25 NOTICE syncd0#syncd: :- getSupportedQueueCounters: FABRIC_QUEUE_STAT_COUNTER: counter SAI_QUEUE_STAT_CURR_OCCUPANCY_BYTES is not supported on queue oid:0x190051500000001, rv: SAI_STATUS_NOT_SUPPORTED
#### Steps to reproduce the issue:
1.
2.
3.

#### Describe the results you received:
Lot of error messages in the syslog

#### Describe the results you expected:
No error messages

#### Output of `show version`:
202205
```
(paste your output here)
```
#### Output of `show techsupport`:

```
(paste your output here or download and attach the file here )
```

**Comment by saksarav-nokia** [comment] 2023-06-22 17:57
Opened BCM csp CS00012300922 and here is the BCM's update

We are not supporting these two objects in SAI DNX:  
 
SAI_QUEUE_STAT_CURR_OCCUPANCY_BYTES
SAI_QUEUE_STAT_CURR_OCCUPANCY_LEVEL

There might be some support there in 7.1, but it was be removed after 9.x for DNX.

No RCI or FIFO monitoring on DNX in the direction of VOQ -> fabric is required. Scheduled nature makes this unnecessary. 

After 9.x we support SAI_QUEUE_STAT_WATERMARK_LEVEL which reads bcmFabricStatQueueLinkMaxWmkLevel which reads FMAL_N_TX_RCI_WMK in DNX.

**Comment by saksarav-nokia** [comment] 2023-06-22 17:57
@arlakshm , created this issue

**Comment by arlakshm** [comment] 2023-06-28 18:14
@kenneth-arista this is the error which was discussing the community today about SAI return error while polling fabric queue counters

**Comment by kenneth-arista** [comment] 2023-07-07 18:02
@jfeng-arista

**Comment by jfeng-arista** [comment] 2023-07-10 16:46
These will not affect fabric link monitoring feature.  They are be displayed in the fabric counters CLI :

> show fabric counters queue 
  ASIC    PORT    STATE    QUEUE_ID    CURRENT_BYTE    CURRENT_LEVEL    WATERMARK_LEVEL
....
     0      17       up           0               0                0                 24

**Comment by kenneth-arista** [comment] 2023-07-10 21:17
Since @jfeng-arista confirmed that these two queue stats are not needed, feel free to remove them. @saksarav-nokia do you want to make the change?

**Comment by saksarav-nokia** [comment] 2023-07-10 21:22
@kenneth-arista , Since this code was added by Arista, i would request Arista to fix this.

**Comment by kenneth-arista** [comment] 2023-07-10 21:26
Okay. We'll follow up with a PR. Thanks for bringing up this issue.

**Comment by kenneth-arista** [comment] 2023-07-12 00:49
@saksarav-nokia I have to backtrack on creating a PR for this because I don't see the issue. If you're testing against 202205 which is using SAI7.1.x, I don't understand how you're reproducing the problem. Can you clarify which DNX SAI version you're using? It's not productive for me to guess a fix that I cannot test.

**Comment by saksarav-nokia** [comment] 2023-07-12 01:15
@kenneth-arista , The errors are seen with 7.1.42.4 SAI
 bcmcmd -n 1 "BCMSAI ver"
BCMSAI ver
BRCM SAI ver: [7.1.42.4], OCP SAI ver: [1.10.2], SDK ver: [sdk-6.5.24]
drivshell>

**Comment by saksarav-nokia** [comment] 2023-07-12 01:23
These errors are seen after the IMM reboot or config reload.

**Comment by arlakshm** [comment] 2023-09-25 22:12
closed by this PR https://github.com/sonic-net/sonic-swss/pull/2862

**Closed by arlakshm** 2023-09-25 22:12 UTC
Labels: Triaged, chassis-voq
