### ISSUE TITLE
TestAutoTechSupport::test_max_limit is failing because files not getting deleted in /var/dump

### ISSUE THREAD

**Issue by kaushiksrivatsav** [sonic-net/sonic-buildimage#17787] opened 2024-01-16 09:34 UTC
#### Description

show_techsupport/test_auto_techsupport.py::TestAutoTechSupport::test_max_limit[techsupport] is failing as it expects to create dummy files of **5% size(750 mb)** each making total of **20%(4 files)** and tries and change the max limit 14% which expects that 2 oldest files to be deleted (to make limit less than **14% 2 files as each file is 5%**), here that those 2 files are not getting deleted.

#### Steps to reproduce the issue:
1.Deploy M0 topology

2.do config load_mingraph on DUT

3.Run show_techsupport  testcase scripts using below command
./run_tests.sh -n ptf6-m -d str-marvell-acs-1 -c show_techsupport/test_auto_techsupport.py::TestAutoTechSupport::test_max_limit[techsupport] -f ../ansible/testbed.csv -i ../ansible/lab,../ansible/veos -t m0,any -u

#### Output of `show version`:

```
root@str-dut-acs-1:/home/admin# show versionSONiC Software Version: SONiC.master.0-dirty-20240112.042828 SONiC OS Version: 12 Distribution: Debian 12.4 Kernel: 6.1.0-11-2-armmp Build commit: 13a16cf87 Build date: Fri Jan 12 04:29:19 UTC 2024 Built by: dut@cpss-arm-vm02Platform: armhf-nokia_ixs7215_52x-r0 HwSKU: Nokia-7215 ASIC: dut ASIC Count: 1 Serial Number: NK204510007 Model Number: 3HE16794AA0101 Hardware Revision: 2 Uptime: 09:47:30 up  4:59,  3 users,  load average: 0.92, 1.17, 1.24 Date: Mon 15 Jan 2024 09:47:30Docker images: REPOSITORY                    TAG                              IMAGE ID       SIZE docker-teamd                  latest                           b9ad6cc8fc14   349MB docker-teamd                  master.0-dirty-20240112.042828   b9ad6cc8fc14   349MB docker-orchagent              latest                           bff5e00febc5   360MB docker-orchagent              master.0-dirty-20240112.042828   bff5e00febc5   360MB docker-nat                    latest                           d4282cd5e5de   351MB docker-nat                    master.0-dirty-20240112.042828   d4282cd5e5de   351MB docker-sflow                  latest                           473ef2228fbb   350MB docker-sflow                  master.0-dirty-20240112.042828   473ef2228fbb   350MB docker-fpm-frr                latest                           dd7555332bfb   371MB docker-fpm-frr                master.0-dirty-20240112.042828   dd7555332bfb   371MB docker-macsec                 latest                           b4b82b19dc7d   351MB docker-eventd                 latest                           ca086cda8c33   331MB docker-eventd                 master.0-dirty-20240112.042828   ca086cda8c33   331MB docker-dhcp-relay             latest                           350b86886f3f   338MB docker-syncd-dut             latest                           efdc512f81d8   440MB docker-syncd-dut             master.0-dirty-20240112.042828   efdc512f81d8   440MB docker-platform-monitor       latest                           14c2d1b3988a   601MB docker-platform-monitor       master.0-dirty-20240112.042828   14c2d1b3988a   601MB docker-sonic-gnmi             latest                           226c3b42c104   404MB docker-sonic-gnmi             master.0-dirty-20240112.042828   226c3b42c104   404MB docker-snmp                   latest                           882176fdfe52   367MB docker-snmp                   master.0-dirty-20240112.042828   882176fdfe52   367MB docker-router-advertiser      latest                           2702606cdb97   332MB docker-router-advertiser      master.0-dirty-20240112.042828   2702606cdb97   332MB docker-lldp                   latest                           18a1055c0939   337MB docker-lldp                   master.0-dirty-20240112.042828   18a1055c0939   337MB docker-mux                    latest                           e72ad58b9a65   344MB docker-mux                    master.0-dirty-20240112.042828   e72ad58b9a65   344MB docker-database               latest                           f0433b9ecc65   332MB docker-database               master.0-dirty-20240112.042828   f0433b9ecc65   332MB docker-sonic-mgmt-framework   latest                           f1b6290c6435   709MB docker-sonic-mgmt-framework   master.0-dirty-20240112.042828   f1b6290c6435   709MB

```

#### Additional information you deem important :

```
validation_files_list = ['sonic_dump_str-dut-acs-1_20240115_084952.tar.gz', 'sonic_dump_str-dut-acs-1_20240115_085023.tar.gz', 'sonic_....tar.gz', 'sonic_dump_str-dut-acs-1_20240115_085218.tar.gz', 'sonic_dump_str-dut-acs-1_20240115_090040.tar.gz'] files_list = ['sonic_dump_str-dut-acs-1_20240115_084952.tar.gz', 'sonic_dump_str-dut-acs-1_20240115_085023.tar.gz'] expected_files = False    def validate_files_in_folder(validation_files_list, files_list, expected_files=True):         """         Validated files in folder         :param validation_files_list: actual number of files in folder(list)         :param files_list: list of files which we will check in folder         :param expected_files: if True - check that file in folder, if False - check that file not in folder         """         with allure.step('Validate files in folder'):             for stub_file in files_list:                 if expected_files:                     err_mgs = 'Expected file: {} not found in available files list: {}'.format(stub_file,                                                                                                validation_files_list)                     assert stub_file in validation_files_list, err_mgs                 else:                     err_msg = 'Unexpected file: {} found in available files list: {}'.format(stub_file,                                                                                              validation_files_list) >                   assert stub_file not in validation_files_list, err_msg E                   AssertionError: Unexpected file: sonic_dump_str-dut-acs-1_20240115_084952.tar.gz found in available files list: ['sonic_dump_str-dut-acs-1_20240115_084952.tar.gz', 'sonic_dump_str-dut-acs-1_20240115_085023.tar.gz', 'sonic_dump_str-dut-acs-1_20240115_085054.tar.gz', 'sonic_dump_str-dut-acs-1_20240115_085116.tar.gz', 'sonic_dump_str-dut-acs-1_20240115_085218.tar.gz', 'sonic_dump_str-dut-acs-1_20240115_090040.tar.gz']err_msg    = "Unexpected file: sonic_dump_str-dut-acs-1_20240115_084952.tar.gz found in available files list: ['sonic_dump_str-...tar.gz', 'sonic_dump_str-dut-acs-1_20240115_085218.tar.gz', 'sonic_dump_str-dut-acs-1_20240115_090040.tar.gz']" expected_files = False files_list = ['sonic_dump_str-dut-acs-1_20240115_084952.tar.gz', 'sonic_dump_str-dut-acs-1_20240115_085023.tar.gz'] stub_file  = 'sonic_dump_str-dut-acs-1_20240115_084952.tar.gz' validation_files_list = ['sonic_dump_str-dut-acs-1_20240115_084952.tar.gz', 'sonic_dump_str-dut-acs-1_20240115_085023.tar.gz', 'sonic_....tar.gz', 'sonic_dump_str-dut-acs-1_20240115_085218.tar.gz', 'sonic_dump_str-dut-acs-1_20240115_090040.tar.gz']show_techsupport/test_auto_techsupport.py:1205: AssertionError  

```

**Comment by vivekrnv** [comment] 2024-01-25 22:28
techsupport cleanup is performed by this script, https://github.com/sonic-net/sonic-utilities/blob/master/scripts/techsupport_cleanup.py

which is invoked during the end of generate_dump script (i.e. show techsupport) https://github.com/sonic-net/sonic-utilities/blob/master/scripts/generate_dump#L2059C5-L2059C19

Any failure in running this script is redirected to /tmp/techsupport_cleanup.log

Can you check syslog and this file to see if you can find any potential root cause of this?

**Comment by dgsudharsan** [comment] 2024-03-07 02:53
@kaushiksrivatsav  Can you please check Vivek's response and provide necessary information?

**Comment by dgsudharsan** [comment] 2024-03-19 04:08
@kaushiksrivatsav  Since we didn't get any requested information we are closing this ticket. Please reopen it if you have additional debug information to share

**Closed by dgsudharsan** 2024-03-19 04:08 UTC
Labels: Triaged, NVIDIA
