### ISSUE TITLE
[sonic-config-engine] /usr/local/bin/db_migrator.py -o migrate fails on all Arista platforms while trying to configure a device for L2 configuration

### ISSUE THREAD

**Issue by vdahiya12** [sonic-net/sonic-buildimage#12083] opened 2022-09-14 23:26 UTC
#### Description

While trying to configure a device for L2 style topology in SONiC OS, the administrator is required to execute a sequential stream of commands as suggested here https://github.com/sonic-net/SONiC/wiki/L2-Switch-mode
while running the first command we see this error for dualtor
```
admin@sonic:~$ cat <<EOF | sudo config reload /dev/stdin -y
> {
>     "MGMT_INTERFACE": {
>         "eth0|1.1.1.1/24": {
>           "gwaddr": "1.1.1.1"
>         }
>     },
>     "DEVICE_METADATA": {
>         "localhost": {
>             "hostname": "sonic",
>             "subtype": "DualToR"
>         }
>     }
> }
> EOF
Running command: rm -rf /tmp/dropstat-*
Disabling container monitoring ...
Stopping SONiC target ...
Running command: /usr/local/bin/sonic-cfggen -j /etc/sonic/init_cfg.json -j /dev/stdin --write-to-db
Running command: /usr/local/bin/db_migrator.py -o migrate
Traceback (most recent call last):
  File "/usr/local/bin/db_migrator.py", line 668, in main
    result = getattr(dbmgtr, operation)()
  File "/usr/local/bin/db_migrator.py", line 627, in migrate
    self.common_migration_ops()
  File "/usr/local/bin/db_migrator.py", line 600, in common_migration_ops
    if self.asic_type == "broadcom" and 'Force10-S6100' in self.hwsku:
TypeError: argument of type 'NoneType' is not iterable
argument of type 'NoneType' is not iterable
usage: db_migrator.py [-h] [-o operation migrate, set_version, get_version] [-s unix socket] [-n asic namespace]

optional arguments:
  -h, --help            show this help message and exit
  -o operation (migrate, set_version, get_version)
                        operation to perform [default: get_version]
  -s unix socket        the unix socket that the desired database listens on
  -n asic namespace     The asic namespace whose DB instance we need to connect
admin@sonic:~$ 
```

#### Steps to reproduce the issue:
1.run the first command as suggested by this wiki link for all SONiC configurations of L2 topology
https://github.com/sonic-net/SONiC/wiki/L2-Switch-mode

#### Describe the results you expected:
**should not see the db_migrator error**

#### Output of `show version`:

```

SONiC Software Version: SONiC.20201231.69
Distribution: Debian 10.12
Kernel: 4.19.0-12-2-amd64
Build commit: f5372f172e
Build date: Fri Jun 24 04:42:05 UTC 2022
Built by: cloudtest@f401f80cc000001

Platform: x86_64-arista_7050cx3_32s
HwSKU: Arista-7050CX3-32S-C32
ASIC: broadcom
ASIC Count: 1
Serial Number: JPE21030951
```
#### Output of `show techsupport`:

```
(paste your output here or download and attach the file here )
```

**Comment by lguohan** [comment] 2022-09-14 23:36
looks like caused by this pr.

https://github.com/sonic-net/sonic-utilities/commit/6dfbdcb665602dadcdb5539bfbf8aa937478fde3

**Comment by prgeor** [comment] 2023-03-01 16:10
> looks like caused by this pr.
> 
> [sonic-net/sonic-utilities@6dfbdcb](https://github.com/sonic-net/sonic-utilities/commit/6dfbdcb665602dadcdb5539bfbf8aa937478fde3)

@tjchadaga could you check if this issue is already fixed

**Comment by tjchadaga** [comment] 2023-05-08 22:02
> > looks like caused by this pr.
> > [sonic-net/sonic-utilities@6dfbdcb](https://github.com/sonic-net/sonic-utilities/commit/6dfbdcb665602dadcdb5539bfbf8aa937478fde3)
> 
> @tjchadaga could you check if this issue is already fixed

This issue is fixed by https://github.com/sonic-net/sonic-buildimage/pull/14933 and https://github.com/sonic-net/sonic-utilities/pull/2821

**Comment by tjchadaga** [comment] 2023-05-30 17:27
Fixed by https://github.com/sonic-net/sonic-utilities/pull/2821

**Closed by tjchadaga** 2023-05-30 17:27 UTC
Labels: Triaged, MSFT
