### ISSUE TITLE
[202211, 202311] image build failed 

### ISSUE THREAD

**Issue by aparkhomenko-xsight** [sonic-net/sonic-buildimage#19123] opened 2024-05-29 07:39 UTC
#### Description

Build of SONiC's .bin image is broken for 202211, 202311 versions (Debian Bullseye based)

It seems like this issue is caused by issue in **requests**  package
https://github.com/docker/docker-py/issues/3256

#### Steps to reproduce the issue:
1. SONIC_BUILD_JOBS=8 SONIC_DPKG_CACHE_METHOD=none make target/sonic-xsight.bin

#### Describe the results you received:

target/sonic-xsight.bin.log

```
 '[' 0 '!=' 0 ']'
+ sudo cp files/build_templates/docker_image_ctl.j2 ./fsroot-xsight/usr/share/sonic/templates/docker_image_ctl.j2
+ sudo LANG=C DOCKER_HOST= chroot ./fsroot-xsight /usr/local/bin/generate_shutdown_order.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/requests/adapters.py", line 555, in send
    conn = self.get_connection_with_tls_context(
  File "/usr/local/lib/python3.9/dist-packages/requests/adapters.py", line 411, in get_connection_with_tls_context
    conn = self.poolmanager.connection_from_host(
  File "/usr/local/lib/python3.9/dist-packages/urllib3/poolmanager.py", line 304, in connection_from_host
    return self.connection_from_context(request_context)
  File "/usr/local/lib/python3.9/dist-packages/urllib3/poolmanager.py", line 326, in connection_from_context
    raise URLSchemeUnknown(scheme)
urllib3.exceptions.URLSchemeUnknown: Not supported URL scheme http+docker

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/docker/api/client.py", line 214, in _retrieve_server_version
    return self.version(api_version=False)["ApiVersion"]
  File "/usr/local/lib/python3.9/dist-packages/docker/api/daemon.py", line 181, in version
    return self._result(self._get(url), json=True)
  File "/usr/local/lib/python3.9/dist-packages/docker/utils/decorators.py", line 46, in inner
    return f(self, *args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/docker/api/client.py", line 237, in _get
    return self.get(url, **self._set_request_timeout(kwargs))
  File "/usr/local/lib/python3.9/dist-packages/requests/sessions.py", line 602, in get
    return self.request("GET", url, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.9/dist-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/requests/adapters.py", line 559, in send
    raise InvalidURL(e, request=request)
requests.exceptions.InvalidURL: Not supported URL scheme http+docker

```

This patch fixes the issue

```
diff --git a/build_debian.sh b/build_debian.sh
index e95904e1f..0b0386531 100755
--- a/build_debian.sh
+++ b/build_debian.sh
@@ -559,6 +559,8 @@ sudo https_proxy=$https_proxy LANG=C chroot $FILESYSTEM_ROOT pip3 install 'wheel
 # docker Python API package is needed by Ansible docker module as well as some SONiC applications
 sudo https_proxy=$https_proxy LANG=C chroot $FILESYSTEM_ROOT pip3 install 'docker==6.1.1'
 
+sudo https_proxy=$https_proxy LANG=C chroot $FILESYSTEM_ROOT pip3 install 'requests<2.32.0'
+
 # Install scapy
 sudo https_proxy=$https_proxy LANG=C chroot $FILESYSTEM_ROOT pip3 install 'scapy==2.4.4'
```

**Comment by aparkhomenko-xsight** [comment] 2024-05-29 14:34
same issue with master branch

**Comment by Prajwal-palc** [comment] 2024-05-30 05:43
You can refer this: https://github.com/sonic-net/sonic-buildimage/issues/19028

**Comment by arlakshm** [comment] 2024-06-05 15:48
@aparkhomenko-xsight, the PR with is merged. Please retry and close if the problem is not there anymore.

**Closed** 2024-06-06 09:05 UTC
