### ISSUE TITLE
FRR may advertise BGP routes before they are programmed in hardware ASIC

### ISSUE THREAD

**Issue by guichuan2018** [sonic-net/sonic-buildimage#17604] opened 2023-12-22 03:09 UTC
#### Description

FRR may advertise BGP routes before they are successfully programmed in hardware ASIC. I may lead to packet drop. To prevent it from happening, there's a need to have an option to not to advertise a BGP route unless it is successfully programed in hardware asic.

#### Steps to reproduce the issue:
1.
2.
3.

#### Describe the results you expected:

Provide a CLI to postpone advertisement of a BGP route until it's successfully programmed in hardware asic.

#### Output of `show version`:

```
(paste your output here)
```
#### Output of `show techsupport`:

```
(paste your output here or download and attach the file here )
```

**Comment by judyjoseph** [comment] 2024-01-03 16:33
@stepanblyschak please add details of the new feature which helps to fix this, thanks.

**Comment by stepanblyschak** [comment] 2024-01-03 18:52
@judyjoseph @guichuan2018 Please check https://github.com/sonic-net/SONiC/blob/master/doc/BGP/BGP-supress-fib-pending.md

**Comment by guichuan2018** [comment] 2024-01-17 17:10
@stepanblyschak good, thanks for the update

**Comment by stepanblyschak** [comment] 2024-03-11 09:51
@guichuan2018 @judyjoseph Can be closed? The feature is planned in 2405

**Comment by guichuan2018** [comment] 2024-03-11 13:33
Definitely , many thanks for the update!

**Comment by volodymyrsamotiy** [comment] 2024-03-19 13:31
Discussed with @stepanblyschak - as mentioned it the comments it is not a bug but a feature which is already merged to "master", so will be supported starting from 202405 release (but can be used even now from "master" branch).
So closing this ticket.

**Closed by volodymyrsamotiy** 2024-03-19 13:31 UTC
Labels: Triaged, NVIDIA
