### ISSUE TITLE
Building for VS fails: OSError: Failed to locate platform directory

### ISSUE THREAD

**Issue by TafkaMax** [sonic-net/sonic-buildimage#18180] opened 2024-02-26 12:03 UTC
#### Description

When trying to build sonic image locally I am getting an error in the tests for **buster** build env. I am using the recommended Ubuntu 20.04 Distro as the builder.

I tried to use the branch `202311` and `master` to build.

#### Steps to reproduce the issue:
1. Ubuntu 20.04 VM
2. .gitlab-ci.yml specified below
```yaml
---
stages:
  - build
variables:
  UNATTENDED: 1
.build_sonic:
  stage: build
  before_script:
    - docker info
    - export PATH="~/.local/bin:$PATH"
    - pip3 install --user j2cli --quiet
    - git clone --recurse-submodules https://github.com/sonic-net/sonic-buildimage.git
    - cd sonic-buildimage
    - git checkout "$CI_COMMIT_REF_NAME"
    - sed -i 's/INCLUDE_ICCPD = n/INCLUDE_ICCPD = y/' rules/config
    - sed -i 's/SONIC_CONFIG_BUILD_JOBS = 1/SONIC_CONFIG_BUILD_JOBS = 4/g' rules/config
  script:
    #- /usr/bin/env make reset
    - make init
    #   - make configure PLATFORM="$PLATFORM" PLATFORM_ARCH="$PLATFORM_ARCH"
    - make configure PLATFORM=$PLATFORM
    - NOSTRETCH=1 NOJESSIE=1 make SONIC_BUILD_JOBS=7 all
  artifacts:
    name: $TARGET
    paths:
      - target/$TARGET
  when: manual
build_sonic_vs_x64:
  extends: .build_sonic
  variables:
    PLATFORM: vs
    PLATFORM_ARCH: amd64
    TARGET: sonic-vs.img.gz
  when: manual
build_sonic_broadcom_x64:
  extends: .build_sonic
  variables:
    PLATFORM: broadcom
    PLATFORM_ARCH: amd64
    TARGET: sonic-broadcom.bin
  when: manual
```

#### Describe the results you received:

```
ERROR: test_mgmt_device_disable_counters (tests.test_minigraph_case.TestCfgGenCaseInsensitive)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/sonic/src/sonic-config-engine/tests/test_minigraph_case.py", line 567, in test_mgmt_device_disable_counters
    result = minigraph.parse_xml(graph_path)
  File "/sonic/src/sonic-config-engine/minigraph.py", line 1581, in parse_xml
    (ports, alias_map, alias_asic_map) = get_port_config(hwsku=hwsku, platform=platform, port_config_file=port_config_file, asic_name=asic_name, hwsku_config_file=hwsku_config_file)
  File "/sonic/src/sonic-config-engine/portconfig.py", line 192, in get_port_config
    port_config_file = device_info.get_path_to_port_config_file(hwsku, asic_id)
  File "/usr/local/lib/python2.7/dist-packages/sonic_py_common/device_info.py", line 412, in get_path_to_port_config_file
    platform_path = get_path_to_platform_dir()
  File "/usr/local/lib/python2.7/dist-packages/sonic_py_common/device_info.py", line 233, in get_path_to_platform_dir
    raise OSError("Failed to locate platform directory")
OSError: Failed to locate platform directory
```

#### Describe the results you expected:

The build to succeed?

#### Output of `show version`:

N/A

#### Output of `show techsupport`:

N/A

#### Additional information you deem important (e.g. issue happens only occasionally):

I have added the `make all` output in a file where the error happens.

[make-output.txt](https://github.com/sonic-net/sonic-buildimage/files/14404196/make-output.txt)

**Comment by TafkaMax** [comment] 2024-03-02 12:47
I am not sure if this is the problem, but I am seeing this error in the build containers.

  `WARNING: The scripts redis-dump and redis-load are installed in '/var/gitlab-runner/.local/bin' which is not on PATH.`

This is happening for lots of installed pkgs.

I checked that `sonic-builder-DISTRIBUTION/Dockerfile.user.j2` sets the user who is building it.

Currently I am trying to add .local/bin to the .bashrc of the build containers to see if it will fix it.

**Comment by TafkaMax** [comment] 2024-03-02 14:23
After trying to add the PATH to: `sonic-slave-buster`  via appending it to the `Dockerfile.user.j2` it did not work as excpected.

I am getting the same errors:

```

[ building ] [ target/python-wheels/buster/sonic_py_common-1.0-py3-none-any.whl-install ] 
  WARNING: The scripts futurize and pasteurize are installed in '/var/gitlab-runner/.local/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  WARNING: The script netaddr is installed in '/var/gitlab-runner/.local/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  WARNING: The scripts json2xml, pyang and yang2html are installed in '/var/gitlab-runner/.local/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
```

Added one of these exempts as an example. While going in the build container via `docker exec -it NAME /bin/bash` I was able to see that my PATH was correct, but maybe make file does not like that?

**Comment by TafkaMax** [comment] 2024-03-02 14:37
I also upgraded the build-env to a Ubuntu 22.04 Jammy release. Have done multiple "refreshes"  deleting old data with rm -rf and docker system prune -a, but to no avail.

**Comment by TafkaMax** [comment] 2024-03-02 14:50
I have a feeling this PATH thing is actually "common" and not related to my issue? I am not 100% sure though.

**Comment by TafkaMax** [comment] 2024-03-02 21:46
I also tried to build for 202305 branch, but to no avail. There was some other error, which I don't want to delve into right now. So I am trying again the 202311 branch.

Why is this sonic repo so cluttered and chaotic :(

Also ran into this issue when trying to make clean https://github.com/sonic-net/sonic-buildimage/pull/18084

**Comment by TafkaMax** [comment] 2024-03-02 21:49
I did add my gitlab-runner user to the sudoers group. via `usermod -aG sudo gitlab-runner` and injected NOPASSWD logic to `/etc/sudoers.d`  via `gitlab-runner ALL=(ALL) NOPASSWD:ALL` to see if it might make these things "happier".

The `.gitlab-ci.yml` file looks like this currently. 
```
---
stages:
  - build

variables:
  UNATTENDED: 1

.build_sonic:
  stage: build
  timeout: 5h
  before_script:
    - docker info
    - export PATH="~/.local/bin:$PATH"
    - pip3 install --user j2cli --quiet
    - git clone --recurse-submodules https://github.com/sonic-net/sonic-buildimage.git
    - cd sonic-buildimage
    - git restore .
    - cd ..
      #- ./apply-patches.sh sonic-buildimage/sonic-slave-buster/Dockerfile.user.j2
      #- ./apply-patches.sh sonic-buildimage/sonic-slave-bullseye/Dockerfile.user.j2
      #- ./apply-patches.sh sonic-buildimage/sonic-slave-bookworm/Dockerfile.user.j2
    - cd sonic-buildimage
    - git checkout "$CI_COMMIT_REF_NAME"
      #- sed -i 's/INCLUDE_ICCPD = y/INCLUDE_ICCPD = n/' rules/config
    - sed -i 's/INCLUDE_ICCPD = n/INCLUDE_ICCPD = y/' rules/config
    - sed -i 's/INCLUDE_RESTAPI = n/INCLUDE_RESTAPI = y/' rules/config
    - sed -i 's/INCLUDE_FIPS ?= y/INCLUDE_FIPS = n/' rules/config
    - sed -i 's/SONIC_CONFIG_BUILD_JOBS = 1/SONIC_CONFIG_BUILD_JOBS = 4/g' rules/config
      #- sed -i 's/SONIC_CONFIG_BUILD_JOBS = 4/SONIC_CONFIG_BUILD_JOBS = 1/g' rules/config
  script:
    - make reset
    - make init
    - make configure PLATFORM=$PLATFORM
    - make list
    - make SONIC_BUILD_JOBS=4 target/sonic-vs.bin
    - make SONIC_BUILD_JOBS=4 target/sonic-vs.img.gz
  artifacts:
    name: $TARGET
    paths:
      - target/$TARGET
  when: manual

build_sonic_vs_x64:
  extends: .build_sonic
  variables:
    PLATFORM: vs
    PLATFORM_ARCH: amd64
    TARGET: sonic-vs.img.gz
  when: manual

build_sonic_broadcom_x64:
  extends: .build_sonic
  variables:
    PLATFORM: broadcom
    PLATFORM_ARCH: amd64
    TARGET: sonic-broadcom.bin
  when: manual

**Comment by TafkaMax** [comment] 2024-03-03 09:59
[sonic-job.log](https://github.com/sonic-net/sonic-buildimage/files/14472423/sonic-job.log)

Added latest build log file. With the same error.

The error seems to happen in the "buster" buildenv on 202311 and master.

**Comment by TafkaMax** [comment] 2024-03-03 10:03
As you can see, the build already fails at `make list` command.

**Comment by TafkaMax** [comment] 2024-03-04 08:02
Updated the issue name for clarification.

I will try to build `202305` again from scratch to see what will happen there. 

With `make reset` and `docker system prune -a` just in case.

**Comment by TafkaMax** [comment] 2024-03-04 09:15
Same error with 202305 clean build.

`docker system prune -a`
`make reset`

Adding log file.
[sonic-build-202305.log](https://github.com/sonic-net/sonic-buildimage/files/14479171/sonic-build-202305.log)

**Comment by liushilongbuaa** [comment] 2024-03-05 09:42
https://github.com/sonic-net/sonic-buildimage/blob/0c44d3ddff510cb977ccfc4a5e6859b450fd92ab/rules/docker-config-engine-buster.dep#L9C3-L9C30
Add '$(DOCKER_CONFIG_ENGINE_BUSTER)_TEST = n' to walkaround.
Maybe @prgeor can help triage the root cause.

**Comment by TafkaMax** [comment] 2024-03-05 17:02
[sonic-build-no-unittests.log](https://github.com/sonic-net/sonic-buildimage/files/14498801/sonic-build-no-unittests.log)

Thanks for the tip! Now there is another failure with the same "failed to locate platform directory". Uploaded the new log file. I will try find a place where to skip these unittests aswell for now.

----

I have switched to a Ubuntu 22.04 VM, but the same problem appeared with 20.04 VM.

I have enabled `host-passthrough` on the VM and it can run nested virtualization if needed.

**Comment by TafkaMax** [comment] 2024-03-06 10:44
I injected some print statements to the `device_info.py` code and got this.

```
platform_env is present and is: vs
platform_env is present and is: vs
platform_env is present and is: vs
platform_env is present and is: vs
platform is present and is: vs
platform_path_host is present and is: /usr/share/sonic/device/vs
```

----

```
________________ TestSfpUtilHelper.test_read_all_port_mappings _________________
self = <tests.sfputilhelper_test.TestSfpUtilHelper object at 0x7f0da69ad850>
    @mock.patch('portconfig.get_hwsku_file_name', mock.MagicMock(return_value=hwsku_json_file))
    def test_read_all_port_mappings(self):
    
        sfputil_helper = sfputilhelper.SfpUtilHelper()
        sfputil_helper.logical = []
        sfputil_helper.logical_to_physical = {}
        sfputil_helper.physical_to_logical = {}
>       sfputil_helper.read_all_porttab_mappings(self.platform_dir, 2)
tests/sfputilhelper_test.py:95: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
sonic_platform_base/sonic_sfp/sfputilhelper.py:106: in read_all_porttab_mappings
    self.read_porttab_mappings(port_map_file, inst)
sonic_platform_base/sonic_sfp/sfputilhelper.py:61: in read_porttab_mappings
    ports, _, _ = get_port_config(hwsku, platform, asic_name=asic_name)
/usr/local/lib/python3.9/dist-packages/portconfig.py:192: in get_port_config
    port_config_file = device_info.get_path_to_port_config_file(hwsku, asic_id)
/usr/local/lib/python3.9/dist-packages/sonic_py_common/device_info.py:419: in get_path_to_port_config_file
    (platform_path, hwsku_path) = get_paths_to_platform_and_hwsku_dirs()
/usr/local/lib/python3.9/dist-packages/sonic_py_common/device_info.py:380: in get_paths_to_platform_and_hwsku_dirs
    platform_path = get_path_to_platform_dir()
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
    def get_path_to_platform_dir():
        """
        Retreives the paths to the device's platform directory
    
        Returns:
            A string containing the path to the platform directory of the device
        """
        # Get platform
        platform = get_platform()
        print('platform is present and is: {}'.format(platform))
    
        # Determine whether we're running in a container or on the host
        platform_path_host = os.path.join(HOST_DEVICE_PATH, platform)
        print('platform_path_host is present and is: {}'.format(platform_path_host))
    
        if os.path.isdir(CONTAINER_PLATFORM_PATH):
            platform_path = CONTAINER_PLATFORM_PATH
        elif os.path.isdir(platform_path_host):
            platform_path = platform_path_host
        else:
>           raise OSError("Failed to locate platform directory")
E           OSError: Failed to locate platform directory
/usr/local/lib/python3.9/dist-packages/sonic_py_common/device_info.py:237: OSError
----------------------------- Captured stdout call -----------------------------
platform_env is present and is: vs
platform_env is present and is: vs
platform_env is present and is: vs
platform_env is present and is: vs
platform is present and is: vs
platform_path_host is present and is: /usr/share/sonic/device/vs
```

**Comment by TafkaMax** [comment] 2024-03-06 12:07
Also added another print function: `CONTAINER_PLATFORM_PATH value is: /usr/share/sonic/platform`

**Comment by lizhijianrd** [comment] 2024-03-13 05:04
Resolved by PR #18321

**Closed by lizhijianrd** 2024-03-13 05:04 UTC
Labels: Triaged

**Comment by TafkaMax** [comment] 2024-03-13 07:32
I started building again. Let's see how far it will take me now! 

I set my config job count to 4. Maybe unsetting it and letting it be default would solve the issue aswell? Let's see anyway.

**Comment by TafkaMax** [comment] 2024-03-13 07:35
OK. It seemed that this specific issue is fixed, but I am getting another error now (Failure), that was also present before. I will make a new issue. 

Thanks for your help BTW!
