### ISSUE TITLE
sonic-db-cli socket option not working when using PING 

### ISSUE THREAD

**Issue by davidpil2002** [sonic-net/sonic-buildimage#17617] opened 2023-12-25 14:30 UTC
**Problem:**
When using the tool `sonic-db-cli -s PING` it's not really using the socket unix option.

I debugged it and it's triggering this function:
src/sonic-swss-common/common/dbconnector.cpp
void RedisContext::initContext(const char *host, int port, const timeval *tv)
instead of the function with the socket unix signature:
void RedisContext::initContext(const char *path, const timeval *tv)

**The root cause looks related to this PR:**
https://github.com/sonic-net/sonic-swss-common/pull/607/files
file:sonic-db-cli/sonic-db-cli.cpp
lines 274 - 291

**More details:**
the usage of the tool shows in the example that this command should be supported
admin@mysetup:~$ sudo sonic-db-cli --help
usage: sonic-db-cli [-h] [-s] [-n NAMESPACE] db_or_op [cmd [cmd ...]]

SONiC DB CLI:

positional arguments:
  db_or_op              Database name Or Unary operation(only PING/SAVE/FLUSHALL supported)
  cmd                   Command to execute in database

optional arguments:
  -h, --help            show this help message and exit
  **-s, --unixsocket      Override use of tcp_port and use unixsocket**
  -n NAMESPACE, --namespace NAMESPACE
                        Namespace string to use asic0/asic1.../asicn

**sudo** needed for commands accesing a different namespace [-n], or using unixsocket connection [-s]

Example 1: sonic-db-cli -n asic0 CONFIG_DB keys \*
Example 2: sonic-db-cli -n asic2 APPL_DB HGETALL VLAN_TABLE:Vlan10
Example 3: sonic-db-cli APPL_DB HGET VLAN_TABLE:Vlan10 mtu
Example 4: sonic-db-cli -n asic3 APPL_DB EVAL "return {KEYS[1],KEYS[2],ARGV[1],ARGV[2]}" 2 k1 k2 v1 v2
**Example 5: sonic-db-cli PING | sonic-db-cli -s PING**
Example 6: sonic-db-cli SAVE | sonic-db-cli -s SAVE
Example 7: sonic-db-cli FLUSHALL | sonic-db-cli -s FLUSHALL

**Comment by judyjoseph** [comment] 2024-01-03 16:47
@judyjoseph  to sync with @qiluo-msft on this

**Comment by liuh-80** [comment] 2024-01-04 01:27
I reproduce this issue on ubuntu devbox and this is not a bug, sonic-db-cli will not use unix socket when hostname is 'redis_chassis.server'.

The c++ version is port latest 202205 python version:
https://github.com/sonic-net/sonic-py-swsssdk/blob/653bdba51750cac95feb3dd47904bf4de2353fec/src/swsssdk/scripts/sonic-db-cli

In the python code:

def handle_single_instance(op, use_unix_socket, inst_info):
    inst_hostname = inst_info['hostname']
    if use_unix_socket and inst_hostname != 'redis_chassis.server':
        inst_unix_socket_path = inst_info['unix_socket_path']
        r = redis.Redis(host=inst_hostname, unix_socket_path=inst_unix_socket_path)

The code been add by this commit:
https://github.com/sonic-net/sonic-py-swsssdk/commit/2cd6236849d194625c014d1c2c370f6d2513eb76

@davidpil2002 , if you are not test the issue on ubuntu devbox, please share me your reproduce steps then I can check again.

**Comment by liuh-80** [comment] 2024-01-04 02:21
@davidpil2002 , I test again on VS image and can't reproduce this issue:

admin@vlab-01:~$ sonic-db-cli -s PING
handleSingleOperation useUnixSocket: 1
handleSingleOperation useUnixSocket: 1
connect client with unix socket: /var/run/redis/redis.sock
handleSingleOperation useUnixSocket: 1
handleSingleOperation useUnixSocket: 1
connect client with unix socket: /var/run/redis/redis.sock
handleSingleOperation useUnixSocket: 1
connect client with unix socket: /var/run/redis/redis.sock
connect client with unix socket: /var/run/redis/redis.sock
handleSingleOperation useUnixSocket: 1
handleSingleOperation useUnixSocket: 1
connect client with unix socket: /var/run/redis/redis.sock
handleSingleOperation useUnixSocket: 1
connect client with unix socket: /var/run/redis/redis.sock
handleSingleOperation useUnixSocket: 1
connect client with unix socket: /var/run/redis/redis.sock
handleSingleOperation useUnixSocket: 1
connect client with unix socket: /var/run/redis/redis.sock
connect client with unix socket: /var/run/redis/redis.sock
handleSingleOperation useUnixSocket: 1
connect client with unix socket: /var/run/redis/redis.sock
handleSingleOperation useUnixSocket: 1
connect client with unix socket: /var/run/redis/redis.sock
connect client with unix socket: /var/run/redis/redis.sock
handleSingleOperation useUnixSocket: 1
connect client with unix socket: /var/run/redis/redis.sock
handleSingleOperation useUnixSocket: 1
connect client with unix socket: /var/run/redis/redis.sock
PONG


Code:

string handleSingleOperation(
    const string& netns,
    const string& db_name,
    const string& operation,
    bool useUnixSocket)
{
    **cout << "handleSingleOperation useUnixSocket: " << useUnixSocket << endl;**
    shared_ptr<DBConnector> client;
    auto host = SonicDBConfig::getDbHostname(db_name, netns);
    string message = "Could not connect to Redis at " + host + ":";
    try
    {
        auto db_id =  SonicDBConfig::getDbId(db_name, netns);
        if (useUnixSocket && db_name != "redis_chassis.server")
        {
            auto db_socket = SonicDBConfig::getDbSock(db_name, netns);
            **cout << "connect client with unix socket: " << db_socket << endl;**
            message += db_name + ": Connection refused";
            client = make_shared<DBConnector>(db_id, db_socket, 0);
        }


So, if you still can reproduce this issue, please check your DB config file, and make sure your db name is not "redis_chassis.server"

**Comment by liuh-80** [comment] 2024-01-11 08:12
@davidpil2002 , do you think we can close this issue because it's not a bug?

**Comment by davidpil2002** [comment] 2024-01-16 07:36
> @davidpil2002 , do you think we can close this issue because it's not a bug?

I will double check again and update, thanks
BTW what its the meaning of "VS" word?

**Comment by liuh-80** [comment] 2024-01-16 07:40
> > @davidpil2002 , do you think we can close this issue because it's not a bug?
> 
> I will double check again and update, thanks BTW what its the meaning of "VS" word?

It's sonic KVM image, the image name is sonic-vs.img

**Comment by liuh-80** [comment] 2024-05-10 08:54
Close because not update for 4 months, and it's not a SONiC bug.

**Closed by liuh-80** 2024-05-10 08:54 UTC
Labels: Triaged, MSFT
