### ISSUE TITLE
[Chassis] Errors seen with a config reload, config load_minigrph or reboot on LC

### ISSUE THREAD

**Issue by mannytaheri** [sonic-net/sonic-buildimage#16787] opened 2023-10-06 18:54 UTC
#### Description
We see many error messages when we do either a config reload, config load_minigraph or a reboot on a J2C+ line card in a multi asics chassis.

#### Steps to reproduce the issue:
1. Do either a config reload, config load_minigraph or reboot on a J2C+ line card

#### Describe the results you received:
We see error messages like the following:
The messages get repeated for every port on the line card

```
Oct  6 16:45:50.072611 ixre-egl-board27 ERR swss1#orchagent: :- handleQueueTable: Port with alias:Ethernet0 not found
Oct  6 16:45:50.072611 ixre-egl-board27 ERR swss1#orchagent: :- doTask: Failed to process invalid QOS task
Oct  6 16:45:50.072633 ixre-egl-board27 ERR swss1#orchagent: :- handleQueueTable: Port with alias:Ethernet0 not found
Oct  6 16:45:50.072633 ixre-egl-board27 ERR swss1#orchagent: :- doTask: Failed to process invalid QOS task
Oct  6 16:45:50.072644 ixre-egl-board27 ERR swss1#orchagent: :- handleQueueTable: Port with alias:Ethernet0 not found
Oct  6 16:45:50.072654 ixre-egl-board27 ERR swss1#orchagent: :- doTask: Failed to process invalid QOS task
Oct  6 16:45:50.072671 ixre-egl-board27 ERR swss1#orchagent: :- handleQueueTable: Port with alias:Ethernet0 not found
Oct  6 16:45:50.072671 ixre-egl-board27 ERR swss1#orchagent: :- doTask: Failed to process invalid QOS task
Oct  6 16:45:50.072688 ixre-egl-board27 ERR swss1#orchagent: :- handleQueueTable: Port with alias:Ethernet0 not found
Oct  6 16:45:50.072688 ixre-egl-board27 ERR swss1#orchagent: :- doTask: Failed to process invalid QOS task
Oct  6 16:45:50.072705 ixre-egl-board27 ERR swss1#orchagent: :- handleQueueTable: Port with alias:Ethernet0 not found
Oct  6 16:45:50.072705 ixre-egl-board27 ERR swss1#orchagent: :- doTask: Failed to process invalid QOS task
Oct  6 16:45:50.072732 ixre-egl-board27 ERR swss1#orchagent: :- handleQueueTable: Port with alias:Ethernet0 not found
Oct  6 16:45:50.072732 ixre-egl-board27 ERR swss1#orchagent: :- doTask: Failed to process invalid QOS task
...
...
...
Oct  6 16:45:51.182566 ixre-egl-board27 ERR swss0#orchagent: :- handleQueueTable: Port with alias:Ethernet280 not found
Oct  6 16:45:51.182578 ixre-egl-board27 ERR swss0#orchagent: :- doTask: Failed to process invalid QOS task
Oct  6 16:45:51.182594 ixre-egl-board27 ERR swss0#orchagent: :- handleQueueTable: Port with alias:Ethernet280 not found
Oct  6 16:45:51.182607 ixre-egl-board27 ERR swss0#orchagent: :- doTask: Failed to process invalid QOS task
Oct  6 16:45:51.182624 ixre-egl-board27 ERR swss0#orchagent: :- handleQueueTable: Port with alias:Ethernet280 not found
Oct  6 16:45:51.182633 ixre-egl-board27 ERR swss0#orchagent: :- doTask: Failed to process invalid QOS task
Oct  6 16:45:51.182649 ixre-egl-board27 ERR swss0#orchagent: :- handleQueueTable: Port with alias:Ethernet280 not found
Oct  6 16:45:51.182662 ixre-egl-board27 ERR swss0#orchagent: :- doTask: Failed to process invalid QOS task
Oct  6 16:45:51.182678 ixre-egl-board27 ERR swss0#orchagent: :- handleQueueTable: Port with alias:Ethernet280 not found
Oct  6 16:45:51.182691 ixre-egl-board27 ERR swss0#orchagent: :- doTask: Failed to process invalid QOS task
Oct  6 16:45:51.182707 ixre-egl-board27 ERR swss0#orchagent: :- handleQueueTable: Port with alias:Ethernet280 not found
Oct  6 16:45:51.182720 ixre-egl-board27 ERR swss0#orchagent: :- doTask: Failed to process invalid QOS task
Oct  6 16:45:51.182736 ixre-egl-board27 ERR swss0#orchagent: :- handleQueueTable: Port with alias:Ethernet280 not found
Oct  6 16:45:51.182748 ixre-egl-board27 ERR swss0#orchagent: :- doTask: Failed to process invalid QOS task
```

#### Describe the results you expected:
No Errors

#### Output of `show version`:
show version

SONiC Software Version: SONiC.20220532.45
SONiC OS Version: 11
Distribution: Debian 11.7
Kernel: 5.10.0-18-2-amd64
Build commit: 447280a621
Build date: Thu Sep 28 09:39:40 UTC 2023
Built by: cloudtest@7022e913c000000

#### Output of `show techsupport`:

```
(paste your output here or download and attach the file here )
```

**Comment by mannytaheri** [comment] 2023-10-09 17:15
@vmittal-msft Have you seen this?

**Comment by saksarav-nokia** [comment] 2023-10-10 15:42
Also we are seeing the following errors after config reload

Oct 10 15:11:59.384636 ixre-egl-board26 ERR swss0#orchagent: :- handleQueueTable: malformed key:ixre-egl-board26|asic1|Ethernet256|0. Must contain 2 tokens
Oct 10 15:11:59.384648 ixre-egl-board26 ERR swss0#orchagent: :- doTask: Failed to process invalid QOS task
Oct 10 15:11:59.384669 ixre-egl-board26 ERR swss0#orchagent: :- handleQueueTable: malformed key:ixre-egl-board26|asic1|Ethernet256|1. Must contain 2 tokens
Oct 10 15:11:59.384669 ixre-egl-board26 ERR swss0#orchagent: :- doTask: Failed to process invalid QOS task
Oct 10 15:11:59.384694 ixre-egl-board26 ERR swss0#orchagent: :- handleQueueTable: malformed key:ixre-egl-board26|asic1|Ethernet256|2. Must contain 2 tokens
Oct 10 15:11:59.384707 ixre-egl-board26 ERR swss0#orchagent: :- doTask: Failed to process invalid QOS task
Oct 10 15:11:59.384726 ixre-egl-board26 ERR swss0#orchagent: :- handleQueueTable: malformed key:ixre-egl-board26|asic1|Ethernet256|3. Must contain 2 tokens
Oct 10 15:11:59.384726 ixre-egl-board26 ERR swss0#orchagent: :- doTask: Failed to process invalid QOS task
Oct 10 15:11:59.384752 ixre-egl-board26 ERR swss0#orchagent: :- handleQueueTable: malformed key:ixre-egl-board26|asic1|Ethernet256|4. Must contain 2 tokens
Oct 10 15:11:59.384767 ixre-egl-board26 ERR swss0#orchagent: :- doTask: Failed to process invalid QOS task
Oct 10 15:11:59.384782 ixre-egl-board26 ERR swss0#orchagent: :- handleQueueTable: malformed key:ixre-egl-board26|asic1|Ethernet256|5. Must contain 2 tokens
Oct 10 15:11:59.384797 ixre-egl-board26 ERR swss0#orchagent: :- doTask: Failed to process invalid QOS task
Oct 10 15:11:59.384814 ixre-egl-board26 ERR swss0#orchagent: :- handleQueueTable: malformed key:ixre-egl-board26|asic1|Ethernet256|6. Must contain 2 tokens
Oct 10 15:11:59.384821 ixre-egl-board26 ERR swss0#orchagent: :- doTask: Failed to process invalid QOS task
Oct 10 15:11:59.384843 ixre-egl-board26 ERR swss0#orchagent: :- handleQueueTable: malformed key:ixre-egl-board26|asic1|Ethernet264|0. Must contain 2 tokens
Oct 10 15:11:59.384843 ixre-egl-board26 ERR swss0#orchagent: :- doTask: Failed to process invalid QOS task
Oct 10 15:11:59.384874 ixre-egl-board26 ERR swss0#orchagent: :- handleQueueTable: malformed key:ixre-egl-board26|asic1|Ethernet264|1. Must contain 2 tokens
Oct 10 15:11:59.384874 ixre-egl-board26 ERR swss0#orchagent: :- doTask: Failed to process invalid QOS task
Oct 10 15:11:59.384898 ixre-egl-board26 ERR swss0#orchagent: :- handleQueueTable: malformed key:ixre-egl-board26|asic1|Ethernet264|2. Must contain 2 tokens
Oct 10 15:11:59.384916 ixre-egl-board26 ERR swss0#orchagent: :- doTask: Failed to process invalid QOS task
Oct 10 15:11:59.384929 ixre-egl-board26 ERR swss0#orchagent: :- handleQueueTable: malformed key:ixre-egl-board26|asic1|Ethernet264|3. Must contain 2 tokens
Oct 10 15:11:59.384949 ixre-egl-board26 ERR swss0#orchagent: :- doTask: Failed to process invalid QOS task
Oct 10 15:11:59.384956 ixre-egl-board26 ERR swss0#orchagent: :- handleQueueTable: malformed key:ixre-egl-board26|asic1|Ethernet264|4. Must contain 2 tokens
Oct 10 15:11:59.384976 ixre-egl-board26 ERR swss0#orchagent: :- doTask: Failed to process invalid QOS task
Oct 10 15:11:59.384991 ixre-egl-board26 ERR swss0#orchagent: :- handleQueueTable: malformed key:ixre-egl-board26|asic1|Ethernet264|5. Must contain 2 tokens
Oct 10 15:11:59.385009 ixre-egl-board26 ERR swss0#orchagent: :- doTask: Failed to process invalid QOS task
Oct 10 15:11:59.385021 ixre-egl-board26 ERR swss0#orchagent: :- handleQueueTable: malformed key:ixre-egl-board26|asic1|Ethernet264|6. Must contain 2 tokens
Oct 10 15:11:59.385037 ixre-egl-board26 ERR swss0#orchagent: :- doTask: Failed to process invalid QOS task

**Comment by saksarav-nokia** [comment] 2023-10-12 01:56
1) config_db has QUEUE config applied to system ports, but  handleQueueTable function doesn't handle the system port.
2)  orchagent adds the port with front panel names as alias for front panel ports and not as system ports, but config_db has QUEUE for system ports even for local ports. So getPort will fail
3) Need to find out how "handleQueueTable: Port with alias:Ethernet0 not found" showing up since the config_db has systme ports and not local port names.

**Comment by saksarav-nokia** [comment] 2023-10-19 15:54
@vmittal-msft , tested with PR https://github.com/sonic-net/sonic-swss/pull/2855 , but seeing errors reported in this issue
Oct  6 16:45:50.072611 ixre-egl-board27 ERR swss1#orchagent: :- handleQueueTable: Port with alias:Ethernet0 not found
Oct  6 16:45:50.072611 ixre-egl-board27 ERR swss1#orchagent: :- doTask: Failed to process invalid QOS task
Oct  6 16:45:50.072633 ixre-egl-board27 ERR swss1#orchagent: :- handleQueueTable: Port with alias:Ethernet0 not found
Oct  6 16:45:50.072633 ixre-egl-board27 ERR swss1#orchagent: :- doTask: Failed to process invalid QOS task
Oct  6 16:45:50.072644 ixre-egl-board27 ERR swss1#orchagent: :- handleQueueTable: Port with alias:Ethernet0 not found
Oct  6 16:45:50.072654 ixre-egl-board27 ERR swss1#orchagent: :- doTask: Failed to process invalid QOS task
Oct  6 16:45:50.072671 ixre-egl-board27 ERR swss1#orchagent: :- handleQueueTable: Port with alias:Ethernet0 not found
Oct  6 16:45:50.072671 ixre-egl-board27 ERR swss1#orchagent: :- doTask: Failed to process invalid QOS task
Oct  6 16:45:50.072688 ixre-egl-board27 ERR swss1#orchagent: :- handleQueueTable: Port with alias:Ethernet0 not found
Oct  6 16:45:50.072688 ixre-egl-board27 ERR swss1#orchagent: :- doTask: Failed to process invalid QOS task
Oct  6 16:45:50.072705 ixre-egl-board27 ERR swss1#orchagent: :- handleQueueTable: Port with alias:Ethernet0 not found
Oct  6 16:45:50.072705 ixre-egl-board27 ERR swss1#orchagent: :- doTask: Failed to process invalid QOS task
Oct  6 16:45:50.072732 ixre-egl-board27 ERR swss1#orchagent: :- handleQueueTable: Port with alias:Ethernet0 not found
Oct  6 16:45:50.072732 ixre-egl-board27 ERR swss1#orchagent: :- doTask: Failed to process invalid QOS task

**Comment by saksarav-nokia** [comment] 2024-03-21 18:28
@vmittal-msft ,  all these issues got fixed right?

**Comment by amitpawar12** [comment] 2024-07-15 20:54
@vmittal-msft 

Steps to reproduce:
1. Issue 'ecnconfig -q 4 on' on the box. One can use option -q 3 as well to see this issue.

```
sudo ip netns exec asic0 ecnconfig -q 4 on
```

2. Logs seen
```
Jul 15 20:49:06.801193 ixre-egl-board73 ERR swss0#orchagent: :- handleQueueTable: malformed key:Ethernet0|4. Must contain 4 tokens
Jul 15 20:49:06.801193 ixre-egl-board73 ERR swss0#orchagent: :- doTask: Failed to process invalid QOS task
Jul 15 20:49:06.801310 ixre-egl-board73 ERR swss0#orchagent: :- handleQueueTable: malformed key:Ethernet8|4. Must contain 4 tokens
Jul 15 20:49:06.801323 ixre-egl-board73 ERR swss0#orchagent: :- doTask: Failed to process invalid QOS task
```

Please let me know if the issue is fixed. Will open a new issue in case the above one is fixed.

Thanks,
-A

**Comment by vmittal-msft** [comment] 2024-08-02 17:55
@amitpawar12  i am looking into this.

**Comment by vmittal-msft** [comment] 2024-08-28 23:26
Original issue has been fixed in latest image. We are no more seeing -
Oct  6 16:45:50.072611 ixre-egl-board27 ERR swss1#orchagent: :- handleQueueTable: Port with alias:Ethernet0 not found
Oct  6 16:45:50.072611 ixre-egl-board27 ERR swss1#orchagent: :- doTask: Failed to process invalid QOS task
Oct  6 16:45:50.072633 ixre-egl-board27 ERR swss1#orchagent: :- handleQueueTable: Port with alias:Ethernet0 not found
Oct  6 16:45:50.072633 ixre-egl-board27 ERR swss1#orchagent: :- doTask: Failed to process invalid QOS task
Oct  6 16:45:50.072644 ixre-egl-board27 ERR swss1#orchagent: :- handleQueueTable: Port with alias:Ethernet0 not found
Oct  6 16:45:50.072654 ixre-egl-board27 ERR swss1#orchagent: :- doTask: Failed to process invalid QOS task
Oct  6 16:45:50.072671 ixre-egl-board27 ERR swss1#orchagent: :- handleQueueTable: Port with alias:Ethernet0 not found
Oct  6 16:45:50.072671 ixre-egl-board27 ERR swss1#orchagent: :- doTask: Failed to process invalid QOS task
Oct  6 16:45:50.072688 ixre-egl-board27 ERR swss1#orchagent: :- handleQueueTable: Port with alias:Ethernet0 not found
Oct  6 16:45:50.072688 ixre-egl-board27 ERR swss1#orchagent: :- doTask: Failed to process invalid QOS task
Oct  6 16:45:50.072705 ixre-egl-board27 ERR swss1#orchagent: :- handleQueueTable: Port with alias:Ethernet0 not found
Oct  6 16:45:50.072705 ixre-egl-board27 ERR swss1#orchagent: :- doTask: Failed to process invalid QOS task
Oct  6 16:45:50.072732 ixre-egl-board27 ERR swss1#orchagent: :- handleQueueTable: Port with alias:Ethernet0 not found
Oct  6 16:45:50.072732 ixre-egl-board27 ERR swss1#orchagent: :- doTask: Failed to process invalid QOS task
...

**Comment by vmittal-msft** [comment] 2024-08-28 23:27
@amitpawar12  please open a separate issue for this -

Steps to reproduce:
Issue 'ecnconfig -q 4 on' on the box. One can use option -q 3 as well to see this issue.
sudo ip netns exec asic0 ecnconfig -q 4 on
Logs seen
Jul 15 20:49:06.801193 ixre-egl-board73 ERR swss0#orchagent: :- handleQueueTable: malformed key:Ethernet0|4. Must contain 4 tokens
Jul 15 20:49:06.801193 ixre-egl-board73 ERR swss0#orchagent: :- doTask: Failed to process invalid QOS task
Jul 15 20:49:06.801310 ixre-egl-board73 ERR swss0#orchagent: :- handleQueueTable: malformed key:Ethernet8|4. Must contain 4 tokens
Jul 15 20:49:06.801323 ixre-egl-board73 ERR swss0#orchagent: :- doTask: Failed to process invalid QOS task

**Comment by vmittal-msft** [comment] 2024-08-28 23:27
We are seeing different set of errors during LC reboot, i will open a separate issue for that.

**Closed** 2024-08-28 23:30 UTC
Labels: P0, Triaged, MSFT
