### ISSUE TITLE
`reboot` on Mellanox platform will return immediately to prompt

### ISSUE THREAD

**Issue by qiluo-msft** [sonic-net/sonic-buildimage#5009] opened 2020-07-21 04:22 UTC
When `reboot`, it will immediately return to shell prompt, and we can run other commands for a while, and then suddenly it reboot. The expected behavior should be no returning.
```
admin@sonic:~$ sudo reboot
admin@sonic:~$
admin@sonic:~$
admin@sonic:~$ which reboot
/usr/bin/reboot
admin@sonic:~$
admin@sonic:~$
admin@sonic:~$ Connection to 10.10.10.10 closed by remote host.
Connection to 10.10.10.10 closed.
```

**Comment by stephenxs** [comment] 2020-07-21 04:43
Hi Qi,
Is it on master or 201911?
If it's on master, I tend to think it's the reproduction of [issue 4305](https://github.com/Azure/sonic-buildimage/issues/4305)

**Comment by qiluo-msft** [comment] 2020-07-21 04:46
I only checked master. It is not the same, please check `which reboot` in my output.

**Comment by madhanmellanox** [comment] 2020-07-23 03:05
The reboot is aliased to /usr/sbin/reboot in super-user mode. Where as in user mode, it is aliased to /usr/bin/root.

In master image,
admin@sonic:~$ echo $PATH
/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games
admin@sonic:~$ which reboot
/usr/bin/reboot
admin@sonic:~$ sudo su
root@sonic:/home/admin# echo $PATH
/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
root@sonic:/home/admin# which reboot
/usr/sbin/reboot
root@sonic:/home/admin#

In 201911 image,
admin@sonic:~$ echo $PATH
/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games
admin@sonic:~$ which reboot
/usr/bin/reboot
admin@sonic:~$ sudo su
root@sonic:/home/admin# echo $PATH
/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
root@sonic:/home/admin# which reboot
/usr/bin/reboot
root@sonic:/home/admin#

**Comment by volodymyrsamotiy** [comment] 2024-03-19 15:13
Looks this issue is not relevant anymore since there is no such issue on latest "master" and also there is explanation by Madhan in comments.
So I am closing this ticket.

**Closed by volodymyrsamotiy** 2024-03-19 15:13 UTC
Labels: Triaged
