### ISSUE TITLE
[Master/202411] RPC builds are broken

### ISSUE THREAD

**Issue by jon-nokia** [sonic-net/sonic-buildimage#20322] opened 2024-09-20 21:41 UTC
#### Description
https://github.com/sonic-net/sonic-sairedis/pull/1409 contained in latest HEAD is causing RPC build failure.

make ENABLE_SYNCD_RPC=y target/docker-syncd-brcm-dnx-rpc.gz

mkdir -p ./src/obj
g++ -I/usr/include/sai -I. -I../../experimental -std=c++11 -DFORCE_BOOST_SMART_PTR -c src/switch_sai_rpc_server.cpp -o src/obj/switch_sai_rpc_server.o -I/usr/include/sai -I. -I../../experimental -std=c++11 -DFORCE_BOOST_SMART_PTR -I./src/gen-cpp
In file included from ../../experimental/saiexperimentaldashvip.h:30,
                 from /usr/include/sai/saiobject.h:40,
                 from /usr/include/sai/sai.h:50,
                 from src/switch_sai_rpc_server.cpp:48:
../../experimental/saitypesextensions.h:37:46: error: 'SAI_OBJECT_TYPE_EXTENSIONS_RANGE_BASE' was not declared in this scope
   37 |     SAI_OBJECT_TYPE_EXTENSIONS_RANGE_START = SAI_OBJECT_TYPE_EXTENSIONS_RANGE_BASE,

#### Steps to reproduce the issue:
1.
2.
3.

#### Output of `show version`:

```
(paste your output here)
```
#### Output of `show techsupport`:

```
(paste your output here or download and attach the file here )
```

**Comment by bingwang-ms** [comment] 2024-09-25 15:41
Issue is seen in master branch when building syncd with rpc enabled.
@kcudnik @liushilongbuaa Can you check if buildteam can help address this issue?

**Comment by liushilongbuaa** [comment] 2024-09-26 06:34
@theasianpianist , please also help to check.

**Comment by arlakshm** [comment] 2024-10-02 20:28
@saksarav-nokia, @jon-nokia Is this issue seen in 202405?

**Comment by jon-nokia** [comment] 2024-10-02 20:39
> @saksarav-nokia, @jon-nokia Is this issue seen in 202405?

No.  I believe 202405 src/sonic-sairedis is still at d3fbec017ef, so has not had update since 5/27.  src/sonic-sairedis commit, 433d039a4 brings in new SAI submodule which causes break.

**Comment by kcudnik** [comment] 2024-10-03 08:32
not sure how this is cauing RPC error, seems like your headers are not updated, in my change you pointed https://github.com/opencomputeproject/SAI/pull/2028/files#diff-444febffce442e4277a1ced22d1ab94df045dfaa10a1b671ee35a7e5c2d9f683R305 this line implements SAI_OBJECT_TYPE_EXTENSIONS_RANGE_BASE, SAI headers build is passing on girhub and locally, also this is passing on sairedis repo where build is also passing, not sure how your build is including headers that are not including correct saitypes.h

**Comment by kcudnik** [comment] 2024-10-03 08:33
can i reporoduce this locally without building entire image ?

**Comment by saksarav-nokia** [comment] 2024-10-03 13:37
@kcudnik , i believe the libsai package installs the sai header files in /usr/include/sai  and sai-thrift includes these header files for build. Since the vendor SAI header files don't have your changes, the build is failing.

**Comment by kcudnik** [comment] 2024-10-03 15:15
so seems like vendor headers needs to be updated, or we need to update rpc build to use local headers, since originally rpc build code is not my code, if i remember correctly they copy /usr/include/sai headers to build rpc instead of local SAI repo headers, thats why it could fail

any suggestions which way we should go ?

**Comment by kcudnik** [comment] 2024-10-03 15:30
problem is here: https://github.com/opencomputeproject/SAI/blob/master/test/saithrift/Makefile#L6 sai headers are taken form /usr/include/sai which are vendor headers, and experimental headers are taken from -I../../experimental as local headers to compile

but im not sure changing 
```
SAI_PREFIX = /usr
SAI_HEADER_DIR ?= $(SAI_PREFIX)/include/sai
SAI_HEADERS = $(SAI_HEADER_DIR)/sai*.h
CFLAGS = -I$(SAI_HEADER_DIR) -I. -I../../experimental -std=c++11
```

will cause some other issues, since SAI_HEADER_DIR is with "?" which means i cloud be override externally before calling makefile, im not sure if DASH is utilizing this feature.

not sure what would be easy fix here, where should we patch 
+@lguohan

**Comment by saksarav-nokia** [comment] 2024-10-08 22:20
@kcudnik ,  I am able to build RPC image for BCM DNX if i change the sai-thrift Makefile to use the experimental header files from /usr/include/sai/experimental. Not sure if all SAI vendors include experimental header files in the libsai package.

**Comment by kcudnik** [comment] 2024-10-09 13:17
> @kcudnik , I am able to build RPC image for BCM DNX if i change the sai-thrift Makefile to use the experimental header files from /usr/include/sai/experimental. Not sure if all SAI vendors include experimental header files in the libsai package.

im not sure that ether, but my proposal was to actually point to SAI/inc since experimental is pointed in
```
CFLAGS = -I$(SAI_HEADER_DIR) -I. -I../../experimental -std=c++11
```

and the issue is with regular includes that are pulled of from /usr/include/sai, so if we would change that SAI_HEADER_DIR  to ../inc during build make then it should be fine

**Comment by saksarav-nokia** [comment] 2024-10-09 13:22
> > @kcudnik , I am able to build RPC image for BCM DNX if i change the sai-thrift Makefile to use the experimental header files from /usr/include/sai/experimental. Not sure if all SAI vendors include experimental header files in the libsai package.
> 
> im not sure that ether, but my proposal was to actually point to SAI/inc since experimental is pointed in
> 
> ```
> CFLAGS = -I$(SAI_HEADER_DIR) -I. -I../../experimental -std=c++11
> ```
> 
> and the issue is with regular includes that are pulled of from /usr/include/sai, so if we would change that SAI_HEADER_DIR to ../inc during build make then it should be fine

Yes. In our local build, we unblocked the build failure by using  ../../inc instead of /usr/include/sai

**Comment by kcudnik** [comment] 2024-10-09 14:21
great, did you changed that in Makefile in SAI repo or in build process of this package in build image?

**Comment by saksarav-nokia** [comment] 2024-10-09 14:25
i changed in sai-thrift Makefile
https://github.com/saksarav-nokia/SAI/commit/2cbd247500264a9c85c148597ad1658478106dc3

**Comment by kcudnik** [comment] 2024-10-09 14:41
yea, but this will limit functionality, will be be able to change the code that is actually calling this Makefile? and pass SAI_HEADER_DIR=../../inc in command line ?

**Comment by liushilongbuaa** [comment] 2024-10-17 10:19
@saksarav-nokia , @kcudnik
What's the status now?

**Comment by saksarav-nokia** [comment] 2024-10-17 12:54
> asked @saksarav-nokia whether he can make change in build [#20322 (comment)](https://github.com/sonic-net/sonic-buildimage/issues/20322#issuecomment-2402541011)

Will there be any functionality impact.  We have tested  with only BCM dnx SAI and it is working fine. How about other SAI vendors.

**Comment by kcudnik** [comment] 2024-10-17 19:15
its hard to say on other vendors, originally this code was added by mlnx

**Comment by kcudnik** [comment] 2024-10-23 17:32
i proposes solution here: https://github.com/sonic-net/sonic-buildimage/issues/20322#issuecomment-2402541011

**Comment by liushilongbuaa** [comment] 2024-10-24 07:21
@kcudnik , who can do the code change? @saksarav-nokia ?
Maybe we can create a PR for test.

**Comment by kcudnik** [comment] 2024-10-24 09:12
guys here already mentioned that they made local change and it works ? so can you raise PR ?

**Comment by liushilongbuaa** [comment] 2024-11-01 02:13
> i proposes solution here: [#20322 (comment)](https://github.com/sonic-net/sonic-buildimage/issues/20322#issuecomment-2402541011)

@kcudnik , so we are waiting for @saksarav-nokia create PR to nokia repo?

**Comment by kcudnik** [comment] 2024-11-04 15:18
@saksarav-nokia please create PR if you already have the fix for this

**Comment by saksarav-nokia** [comment] 2024-11-04 16:22
> @saksarav-nokia please create PR if you already have the fix for this

Yes. I will create the PR

**Comment by kcudnik** [comment] 2024-11-05 11:41
> @kcudnik , I have created the PR. Pls review it

Approved, but please provide more explanation in that pr description why this fix is made

**Comment by saksarav-nokia** [comment] 2024-11-05 15:12
> > @kcudnik , I have created the PR. Pls review it
> 
> Approved, but please provide more explanation in that pr description why this fix is made

@kcudnik , Added more explanation . Pls check

**Comment by kcudnik** [comment] 2024-11-06 08:03
merged

**Comment by adyeung** [comment] 2024-11-13 23:07
@kcudnik when can the Makefile fix from @saksarav-nokia made into SONiC? Latest SONiC broadcom daily build still failing for the same, let me know if there is anything I missed 

https://dev.azure.com/mssonic/build/_build/results?buildId=694058&view=logs&j=88ce9a53-729c-5fa9-7b6e-3d98f2488e3f&t=b71397ab-4d88-53c1-4db7-b4fc5ec36f6f

**Comment by kcudnik** [comment] 2024-11-14 08:45
@saksarav-nokia have you made fix?

**Comment by saksarav-nokia** [comment] 2024-11-14 11:55
Yes, https://github.com/opencomputeproject/SAI/pull/2097

**Comment by adyeung** [comment] 2024-11-14 19:13
@kcudnik can someone help pickup the fix for sonic-sairedis? Broadcom daily build on master branch has been failing, we need to fix this before 202411 branch off

**Comment by adyeung** [comment] 2024-11-14 19:17
FYI @zhangyanzhao @yuezhoujk @tjchadaga

**Comment by kcudnik** [comment] 2024-11-14 20:02
so 2020405 is using SAI v1.14, and that change is on top on v1.15 branch so probably we need to add v1.14.1 version withc that change cherrypicked @tjchadaga @rlhui will that be ok ?

**Comment by tjchadaga** [comment] 2024-11-14 21:16
> so 2020405 is using SAI v1.14, and that change is on top on v1.15 branch so probably we need to add v1.14.1 version withc that change cherrypicked @tjchadaga @rlhui will that be ok ?

@kcudnik, currently, the build is currently only broken for master. 202405 which is using v1.14 is building fine. Do we still need this PR cherry-picked to v1.14?

**Comment by adyeung** [comment] 2024-11-15 20:04
@kcudnik @tjchadaga @rlhui is there a decision? This is needed in master branch to fix broadcom daily build

**Comment by adyeung** [comment] 2024-11-15 20:05
FYI @yuazhe @zhangyanzhao @eddieruan-alibaba 202411 release team

**Comment by kcudnik** [comment] 2024-11-17 22:59
https://github.com/sonic-net/sonic-sairedis/pull/1462 merged updated submodule on sairedis, i will prepare update on buildimage master

**Comment by kcudnik** [comment] 2024-11-18 11:17
i think it will be safer to create new tag on v1.14.1 SAI that will cherrypick taht RCP change

**Comment by kcudnik** [comment] 2024-11-18 11:53
I added v1.14.1 SAI version with included rpc fix https://github.com/opencomputeproject/SAI/commits/v1.14/

**Comment by kcudnik** [comment] 2024-11-18 12:56
updated sairedis: https://github.com/sonic-net/sonic-sairedis/pull/1464, as soon as this passes, i will update buildimage

**Comment by kcudnik** [comment] 2024-11-18 20:57
Added 2 fixes:
https://github.com/sonic-net/sonic-buildimage/pull/20842
https://github.com/sonic-net/sonic-buildimage/pull/20843

hope this will help

**Comment by kcudnik** [comment] 2024-11-19 07:52
@jon-nokia  are those the branches you see this issues? i posted 2 updates for master and 202405 on buildimage, please confirm

**Comment by saksarav-nokia** [comment] 2024-11-19 16:01
@kcudnik , The RPC build was failing only in master and not in 202405

**Comment by kcudnik** [comment] 2024-11-19 16:40
this is actually interesting ,i checked origin/v1.14.0 vs origin/v1.15.0 branches, and none of them is touching Makefile for thiriftserver, so if master on buildimage is failing on broadcom and not on on 202405, that means this thiift server Makefile have no role in compilation, it must be then some header issue in brcm implementation

**Comment by kcudnik** [comment] 2024-11-19 18:37
ok, got it

**Comment by tjchadaga** [comment] 2024-12-18 06:10
Issue is fixed with SAI header update and RPC is getting built on both master and 202405

**Closed by tjchadaga** 2024-12-18 06:10 UTC
Labels: Help Wanted :sos:, Triaged, Master Branch Quality
