### ISSUE TITLE
Memory Leak seems to cause switch to reboot every 6 days on Mellanox SN2100

### ISSUE THREAD

**Issue by sarhaynes** [sonic-net/sonic-buildimage#18949] opened 2024-05-13 16:32 UTC
#### Description

Mellanox SN2100 crashes every 6 days due to out-of-memory condition.

#### Steps to reproduce the issue:
1. No special steps.
2.
3.

#### Describe the results you received:
System crashes and reboots causing temporary loss of storage network.

#### Describe the results you expected:
System not to crash.

#### Output of `show version`:

```
SONiC Software Version: SONiC.202311.537097-4962460ba
SONiC OS Version: 11
Distribution: Debian 11.9
Kernel: 5.10.0-23-2-amd64
Build commit: 4962460ba
Build date: Thu May  2 11:34:36 UTC 2024
Built by: AzDevOps@vmss-soni003L6R

Platform: x86_64-mlnx_msn2100-r0
HwSKU: ACS-MSN2100
ASIC: mellanox
ASIC Count: 1
Serial Number: MT2344T004W8
Model Number: MSN2100-CB2RO
Hardware Revision: A3
Uptime: 12:12:02 up 10:22,  1 user,  load average: 0.87, 0.71, 0.60
Date: Mon 13 May 2024 12:12:02

Docker images:
REPOSITORY                    TAG                       IMAGE ID       SIZE
docker-syncd-mlnx             202311.537097-4962460ba   a5d929a4a37a   874MB
docker-syncd-mlnx             latest                    a5d929a4a37a   874MB
docker-platform-monitor       202311.537097-4962460ba   aa555c270a12   863MB
docker-platform-monitor       latest                    aa555c270a12   863MB
docker-dhcp-relay             latest                    b98941a0e276   310MB
docker-macsec                 latest                    f3dee682bedf   329MB
docker-eventd                 202311.537097-4962460ba   7db838950e76   301MB
docker-eventd                 latest                    7db838950e76   301MB
docker-orchagent              202311.537097-4962460ba   081de3b50bf0   339MB
docker-orchagent              latest                    081de3b50bf0   339MB
docker-fpm-frr                202311.537097-4962460ba   6dd5bd75ec40   359MB
docker-fpm-frr                latest                    6dd5bd75ec40   359MB
docker-nat                    202311.537097-4962460ba   bc91137bdfd9   330MB
docker-nat                    latest                    bc91137bdfd9   330MB
docker-sflow                  202311.537097-4962460ba   d45942ce4ece   328MB
docker-sflow                  latest                    d45942ce4ece   328MB
docker-teamd                  202311.537097-4962460ba   8395c21168d0   327MB
docker-teamd                  latest                    8395c21168d0   327MB
docker-snmp                   202311.537097-4962460ba   cc4f6dec42f8   340MB
docker-snmp                   latest                    cc4f6dec42f8   340MB
docker-router-advertiser      202311.537097-4962460ba   f12e6c87ab1d   301MB
docker-router-advertiser      latest                    f12e6c87ab1d   301MB
docker-lldp                   202311.537097-4962460ba   eee2a7679abe   343MB
docker-lldp                   latest                    eee2a7679abe   343MB
docker-mux                    202311.537097-4962460ba   46f0ebc84f6c   349MB
docker-mux                    latest                    46f0ebc84f6c   349MB
docker-database               202311.537097-4962460ba   18eaf9c0ae4d   301MB
docker-database               latest                    18eaf9c0ae4d   301MB
docker-sonic-gnmi             202311.537097-4962460ba   d1b30a4eebec   389MB
docker-sonic-gnmi             latest                    d1b30a4eebec   389MB
docker-sonic-mgmt-framework   202311.537097-4962460ba   15e5eb518340   416MB
docker-sonic-mgmt-framework   latest                    15e5eb518340   416MB
```

#### Output of `show techsupport`:
Unable to attach files (Something is Blocking the .tar.gz files).
Can make files available if there is a location to upload the files...

**Comment by sarhaynes** [comment] 2024-05-13 16:32
[Uploading sonic_dump_swod2p1650sw03_20240513_121445.tar.gz…]()

**Comment by sarhaynes** [comment] 2024-05-13 16:35
[Uploading sonic_dump_swod2p1650sw03_20240513_121445.tar.gz…]()

**Comment by mbze430** [comment] 2024-05-13 19:25
I am glad I am not the only person reporting this.... it's happening on the Celestica DX010 on 202311

**Comment by dvouilloz** [comment] 2024-05-15 18:56
I have the same problem with a Mellanox SN2010.
In my case it is linked to the pmon container problem.
https://github.com/sonic-net/sonic-buildimage/issues/17025

**Comment by sarhaynes** [comment] 2024-05-16 19:11
> I have the same problem with a Mellanox SN2010. In my case it is linked to the pmon container problem. #17025

I looked at this issue it seems it may be the same problem.  I have added ```docker restart pmon``` to my cron.daily and will continue to monitor.

**Comment by gechiang** [comment] 2024-05-22 15:13
looks like a duplicate of #17025 which is already triaged and assigned.
Closing this one as duplicate.

**Closed by gechiang** 2024-05-22 15:13 UTC
