### ISSUE TITLE
[yang] sonic-mirror-session.yang does not align with ConfigDb

### ISSUE THREAD

**Issue by ganglyu** [sonic-net/sonic-buildimage#12397] opened 2022-10-13 23:58 UTC
#### Description

sonic-mirror-session.yang uses leaf-list for for src_port:
https://github.com/sonic-net/sonic-buildimage/blob/master/src/sonic-yang-models/yang-models/sonic-mirror-session.yang#L157

But src_port is not a list in ConfigDB:
admin@vlab-01:~$ sudo config mirror_session erspan add mrr_port 1.2.3.4 20.21.22.23 8 100 1234 0 Ethernet0

admin@vlab-01:~$ redis-cli -n 4 hgetall "MIRROR_SESSION|mrr_port"
 1) "type"
 2) "ERSPAN"
 3) "src_ip"
 4) "1.2.3.4"
 5) "dst_ip"
 6) "20.21.22.23"
 7) "dscp"
 8) "8"
 9) "ttl"
10) "100"
11) "gre_type"
12) "1234"
13) "queue"
14) "0"
15) "src_port"
16) "Ethernet0"
17) "direction"
18) "BOTH"

#### Steps to reproduce the issue:
1. Config MIRROR_SESSION table
2. Dump ConfigDB

#### Describe the results you received:
sonic-mirror-session.yang does not align with ConfigDb

#### Describe the results you expected:
SONiC Yang should align with ConfigDB

#### Output of `show version`:

```
(paste your output here)
```
#### Output of `show techsupport`:

```
(paste your output here or download and attach the file here )
```

**Comment by qiluo-msft** [comment] 2022-10-14 00:23
@praveen-li @Junchao-Mellanox Could you help investigate this issue? It is similar to port lanes attribute.

**Comment by Junchao-Mellanox** [comment] 2022-10-14 09:51
I suppose this is by design. Redis hash type does not support `list` value. So, any field defined as `leaf-list` will be translated into a comma separated string. @praveen-li , correct me if I am wrong.

**Comment by ganglyu** [comment] 2022-10-21 00:14
@rupesh-k will fix this issue

**Comment by qiluo-msft** [comment] 2022-11-18 01:15
@rupesh-k any update?

**Comment by zhangyanzhao** [comment] 2022-12-08 18:07
@rupesh-k  @adyeung  would you please help to provide an update on this issue? Thanks.

**Comment by zhangyanzhao** [comment] 2023-01-19 18:06
@adyeung  any progress on this PR? Thanks.

**Comment by adyeung** [comment] 2023-01-19 21:51
Expecting a fix from rupesh-k by 1/26

**Comment by zhangyanzhao** [comment] 2023-03-09 18:40
PR is merged and close this issue.

**Closed by zhangyanzhao** 2023-03-09 18:40 UTC
Labels: Triaged, yang, BRCM
